### ISSUE TITLE
Sezione 7.5.2 ESEMPIO vacante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#100]
**Description**
Nella sezione 7.5.2 c'è un paragrafo esempio vuoto (Subito prima di 7.5.3) secondo si hanno due possibilità: 
1) Cancellare Esempio
2) Aggiungere in Esempio il riferimento alla figura: Un esempio di audit plan per prendere confidenza con il suo gergo può essere trovato in figura 7.2 

In ogni caso credo che all'interno del testo il riferimento alla figura farebbe bene

**Other issues**

**Comment by mzanella** [comment]
Per me la seconda
