### ISSUE TITLE
Capability Maturity Level Ripetuto più volte

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#107]
**Description**
All'inizio del capitolo 9 si parla di Cabability Maturity Model.
Dopo un po' di robe sul COBIT si hanno il capitolo 9.2.1.5 e la figura 9.4 che sostanzialmente ripetono quanto detto prima. 

Secondo voi si può fare qualcosa o è troppo difficile sistemare ed è meglio tenere cosí?
**Other issues**

**Comment by herrBez** [comment]
@mzanella @Polpetta . Inoltre guardando le slide mi sembra di capire che:

> ISACA’s COBIT uses the CMM approach to rate auditee performance by the
maturity of their control environment.`  

Quindi a dir la verità l'apparente seconda ripetizione del CMM è a dir la verità qualcosa legato più al COBIT e quindi non è una ripetizione vera e propria

**Comment by herrBez** [comment]
Per me si puó anche chiudere. Che dite @Polpetta @mzanella

**Comment by mzanella** [comment]
Va bene chiudiamo

**Comment by herrBez** [comment]
Se qualcuno vorrà la riaprirà ^^
