### ISSUE TITLE
Non è chiaro quali siano i 5 indicatori 

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#108]
**Description**
> Esistono cinque indicatori per capire se l’azienda ha fatto un buon lavoro nel
veicolare i propri obiettivi ai lavoratori. È importante che i dipendenti sappiano
dare risposte a cosa è allineata la compagnia, qual è la sua missione, visione, valori,
obiettivi e strategie. Quando un dipendente non lo sa o risponde “solo per i soldi” è
un segnale negativo

Prendendo solo il testo non si capisce quali siano i 5 indicatori per capire se l'azienda ha fatto un buon lavoro
**Other issues**

**Comment by Polpetta** [comment]
Si l'avevo fatta in maniera discorsiva per evitare un altro elenco puntato 😅
