### ISSUE TITLE
Duplicazione figure 14.3 e 14.5

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#112]
**Description**
Queste due immagini oltre a comparire due volte a distanza di due pagina hanno didascalie diverse
**Other issues**

**Comment by herrBez** [comment]
@mzanella @Polpetta

**Comment by herrBez** [comment]
Cosa ne pensate?

**Comment by Polpetta** [comment]
Secondo me è meglio togliere la 14.5, così si risparmia anche una pagina!
