### ISSUE TITLE
Negli esercizi con una sola domanda eviterei l'1.

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#118]
**Description**

Negli esercizi formati da una domanda sola c'é comunque un elenco puntato. 
![image](https://user-images.githubusercontent.com/6976484/29239071-b5cfab86-7f44-11e7-8fde-7fa43082ef3c.png)
Secondo me sarebbe più carino se l'uno non ci fosse

Si può fare qualcosa (credo di averne già parlato con @Polpetta, ma non ricordo esattamente)

**Other Issues**

**Comment by Polpetta** [comment]
È così la struttura degli esercizi non ci posso fare nulla :/ non è un
elenco puntato, è un comando che devi dare per legare la risposta alla
domanda

Il 12 ago 2017 09:59, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Non è possibile (per i posteri :stuck_out_tongue_winking_eye: ) scrivere un proprio ambiente degli esercizi per evitare la cosa?

**Comment by Polpetta** [comment]
Non sono ancora arrivato a quel livello li 😅 se capisci come fare un
package in LaTeX poi possiamo fare qualcosa, il fatto è che se cambiamo
pacchetto dobbiamo anche cambiare la sintassi di tutti gli esercizi ed è un
po' lunghetta secondo me 😅

Il 12 ago 2017 10:17, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
no se usi `\renewcommand` :smiling_imp:

**Comment by herrBez** [comment]
Chiudo la issue, perchè non ha una priorità infima in questo momento :smile:
