### ISSUE TITLE
Mistranslation esercizio 56

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#119]
**Description**
La domanda originale:

> The difference between where an organization performs and
where they intend to perform is known as:

L'attuale traduzione:

> La differenza tra dove una organizzazione rende e dove loro vorrebbero rendere è anche conosciuto come:

Suona un po' strano il "dove" in italiano. Io la cambierei così:

> La differenza tra quanto un'organizzazione rende e quanto vorrebbe rendere è anche conosciuta come:

**Other issues**

**Comment by Polpetta** [comment]
È meglio la tua traduzione! Aggiornarla pure! :blush:

Il 12 ago 2017 10:20, "herrBez" <notifications@github.com> ha scritto:
