### ISSUE TITLE
Aggiungere risposta corretta alla risposta 74

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#12]
Aggiungere la risposta alla domanda 74 

***What technique would not be appropriate in avoiding OS command injection?***
1. Separate control information from data information
2. Use library
3. Run code in “jail” or other sandbox environment
4. Use a hard-coded password to enable access

**Comment by herrBez** [comment]
Chiudiamo l'issue perchè abbiamo avuto conferma della risposta 4

**Comment by Polpetta** [comment]
Ok

Il 10 lug 2017 23:59, "herrBez" <notifications@github.com> ha scritto:
