### ISSUE TITLE
Footnote non chiara

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#120]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29239178-137a394c-7f48-11e7-891d-d4b60484327a.png)

Non capisco cosa voglia dire la footnote ... 

**Other issues**

**Comment by Polpetta** [comment]
Neanche io, ma è quello che ha detto il prof in classe :/

Il 12 ago 2017 10:22, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Secondo me buttata così non ha tanto senso. Cosa facciamo la eliminiamo?

**Comment by Polpetta** [comment]
Boh sentiamo @mzanella cosa dice

Il 15 ago 2017 08:48, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Forse potremmo sostituire il contenuto della footnote con la definizione di `standard` e `guideline` del libro:

**​Standard** 
Specifies a minimum level of mandatory compliance to ensure uniform consistency with integrity.

**Guideline**
A list of recommendations to follow in the absence of an existing standard.

**Policy**
A high-level statement by management specifying an objective that requires mandatory compliance for all persons of lower authority.

**Procedure**
​A mandatory set of steps used as a cookbook recipe for a desired result. Procedures provide the day-to-day low-level execution necessary to support a standard.

Perchè se si prende questa definizione è chiaro che la risposta è standard perchè stiamo riportando un livello minimo di sicurezza.

Anche in virtù del fatto che si parla di standard solo negli esercizi :sweat_smile:

**Comment by Polpetta** [comment]
Ok, va bene. Secondo me ci sta un footnote che descrive queste cose così uno può anche capire il perché della risposta.
