### ISSUE TITLE
Domanda Esercizio 78 - Alternativa mancante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#122]
**Description**
L'ultima alternativa dell'esercizio 78 è attualmente (negli appunti per via di overleaf penso):

> ClClefly uch as UTF-8defined code suche as UTF-8

Nell'originale è 

> Clearly defined code such as UTF-8

Personalmente però non saprei come tradurla decentemente in italiano. 
Qualcuno ha dei consigli? 
**Other issues**

**Comment by mzanella** [comment]
@herrBez io metterei:
>Definire UTF-8 come codifica

**Comment by herrBez** [comment]
Perfetto. Ma teniamo in inglese le altre alternative dell'esercizio 78?

**Comment by Polpetta** [comment]
Se sono in inglese ma in corsivo significa che non le ho tradotte apposta,
probabilmente perché o non avevo voglia o non trovavo una traduzione che
avesse senso

Il 15 ago 2017 08:47, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
A dirla tutta non sono in corsivo..
![image](https://user-images.githubusercontent.com/6976484/29353013-1991c538-8269-11e7-97e7-086745b6567d.png)

Ma sinceramente suona un po' male:
1. Testo in chiaro
2. Crittazione e controllo dell'integrità
3. \textit{Sanitization}
4. Definire UTF-8 come codifica

O no? 

Fatemi sapere che cosí cerchiamo di chiudere l'issue @mzanella @Polpetta

**Comment by Polpetta** [comment]
Metti tutto in corsivo tranne la 4 che secondo me ci sta in italiano
