### ISSUE TITLE
Traduzione erronea di batch totals

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#125]
**Description**
Nella domanda 85 si legge:

> I lotti totali potrebbero non corrispondere quando transazioni erronee sono rimosse

Mentre l'originale:

> Batch totals may not match when error transactions are removed. 

Non penso che lotti totali sia la traduzione corretta. Infatti penso che in questo caso "totals" significhi somma, importo  `http://www.wordreference.com/enit/totals` e non il numero totale.
Inoltre eviterei di tradurre batch visto che nella domanda precedente si usa direttamente batch. 

Lo stesso discorso dovrebbe valere per la domanda 83 in cui `hash totals` è stato tradotto con `hash totale`. Per stare sul sicuro terrei `batch totals` in 85 e `hash totals` in 83
**Other issues**

**Comment by herrBez** [comment]
Inoltre se si usa la traduzione di batch totals come somma (a guisa di checksum) potrebbe anche spiegare il significato della frase:

> I lotti totali potrebbero non corrispondere quando transazioni erronee sono rimosse

Cioé che se togli qualche transazioni hai che la checksum non corrisponde più

**Comment by mzanella** [comment]
@herrBez va bene se riscivo così:
> Le somme dei batch potrebbero non corrispondere quando transazioni erronee sono rimosse

oppure è meglio:
>I totali dei batch potrebbero non corrispondere quando transazioni erronee sono rimosse

?

**Comment by herrBez** [comment]
Per me la prima va meglio ma metterei tra parentesi il termine inglese in corsivo:

> Le somme dei batch (\textit{batch totals}) potrebbero non corrispondere quando delle transazioni erronee vengono rimosse

Perché magari all'esame viene riportato il termine inglese e non riusciamo a capire (almeno io xD)

**Comment by Polpetta** [comment]
Perché no un footnote?

Il 15 ago 2017 08:42, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Io non sono un grande amante delle footnote. Mi risulta difficile continuare a leggere in maniera fluida. Però se preferisci cosí va bene anche la footnote ..
Cosa ne pensi @mzanella ?
