### ISSUE TITLE
Latex found 2 multiply defined reference(s)

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#127]
**Description**
Latex da il warning `Latex found 2 multiply defined reference(s)`. È normale o è veramente un problema?
**Other issues**

**Comment by Polpetta** [comment]
Ci sono due tag doppiamente definiti sul serio, basta rinominare i doppioni
(dopo averli trovati ovviamente)

Il 15 ago 2017 08:28, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Secondo il log file `fig:testing:facilities:parallel` e `fig:audit:hooks` sono definite più volte.

Entrambi i doppioni si trovano nel file 30- ... 

Ora sistemo :) volevo solo descrivere l'issue

**Comment by Polpetta** [comment]
Rinominane uno ma guarda che poi non ci siano due punti di domanda nel
documento (??) altrimenti significa che si è rotta qualche ref

Il 15 ago 2017 08:33, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Non ci sono ref a quelle immagini, altrimenti ci saremmo accorti dei doppioni ^^

**Comment by Polpetta** [comment]
Allora rinomina e siamo apposto 😅

Il 15 ago 2017 08:37, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Ho fatto la pull request ^^

**Comment by Polpetta** [comment]
Ok appena posso la guardo!:)

Il 15 ago 2017 09:08, "herrBez" <notifications@github.com> ha scritto:
