### ISSUE TITLE
Aggiungere risposta 37

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#13]
Manca la risposta all'esercizio 37
***La diligenza dovuta (due diligence) si assicura che:***
1. Una organizzazione abbia esercitato le migliori pratiche di sicurezza
possibili in accordo alle migliori pratiche
2. Una organizzazione abbia esercitato in maniera accettabile le pratiche
di sicurezza riguardo a tutte le aree di sicurezza
3. Una organizzazione abbia implementato la gestione del rischio e abbia
messo in pratica tutti i controlli necessari
4. Una organizzazione abbia nominato un Chief Information Security
Officier che sia responsabile della sicurezza degli asset informativi

**Comment by Polpetta** [comment]
Ho messa quella che abbiamo ricevuto su Slack, ovvero la risposta 4.
Chiudo!

**Comment by Polpetta** [comment]
Riapro perchè non è la risposta esatta!

**Comment by Polpetta** [comment]
Segno la 2 infine
