### ISSUE TITLE
Aggiungere la risposta alla domanda 64

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#14]
Aggiungere la risposta alla seguente domanda:
***La documentazione che non viene vista dall’IT Strategy Commitee dovrebbe
essere:***
1. IT Project Plans
2. Analisi del rischio & Analisi dell’impatto sul business
3. IT Balanced Scorecard
4. IT Policies

**Comment by Polpetta** [comment]
Ma non abbiamo la risposta esatta vero?

**Comment by herrBez** [comment]
No, ho chiesto su slack. Nei nostrii appunti non c'è niente

**Comment by Polpetta** [comment]
Alla fine gli abbiamo messo una risposta?

**Comment by mzanella** [comment]
No

**Comment by Polpetta** [comment]
Non bene

**Comment by Polpetta** [comment]
Quindi che si fa? @herrBez

**Comment by herrBez** [comment]
Boh direi di chiedere a Di Pietro, usando però la versione inglese delle slide

**Comment by Polpetta** [comment]
Certo!

**Comment by Polpetta** [comment]
Comunque si slack era la 1, quindi boh piuttosto di niente metterei quella

**Comment by Polpetta** [comment]
@mzanella @herrBez mi mandate il testo originale della domanda per favore? Non so in che slide sia, però al prof volevo mandare la domanda originale

**Comment by mzanella** [comment]
Project Plans.  infatti l'IT Strategy Committee è il comitato di piu' alto livello nel contesto IT, ed e' quindi interessato a documentazione di alto livello, come analisi del rischio, BIA, IT Balanced Scorecard, e documenti di policy. I piani implementativi di dettaglio relativi alle strategie IT, non sono nello scope.

**Comment by Polpetta** [comment]
Ciao, riesci ad aggiungere un footnote con la spiegazione alla domanda? Non
ho guardato, se l'hai già fatto lascia perdere sto messaggio

Il 17 ago 2017 18:31, "mzanella" <notifications@github.com> ha scritto:
