### ISSUE TITLE
Mettere le soluzioni agli esercizi DOPO gli esercizi

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#15]
Mettere le risposte esatte **_dopo_** gli esercizi, cosi ci si puo' preparare a mo di quiz della patente

**Comment by Polpetta** [comment]
In teoria @mzanella ha fatto

**Comment by mzanella** [comment]
Non ho modificato il documento, ho creato lo script per farlo. Se preferite che sia sempre cosi lo faccio girare e pusho

**Comment by Polpetta** [comment]
Fatto
