### ISSUE TITLE
Parte (a me) non chiara

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#159]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29449732-2e8b8ebc-83fc-11e7-8e45-0e06a4a95d5d.png)

Non mi è chiarissima la formula. Qualcuno riesce a spiegarmela? (In particolare $K$ cos'è?)
**Other issues**

**Comment by Polpetta** [comment]
Non saprei dirti sinceramente, spero solo che non la chieda 😂 Lo so, non era la risposta che ti aspettavi

**Comment by herrBez** [comment]
E se modificassimo sto paragrafando prendendo spunto da 
![image](https://user-images.githubusercontent.com/6976484/29489959-fa48b89a-852d-11e7-9eeb-a3d6cea0432a.png)
Cancellando l'esempio senza molto senso?
Cosa dite? @mzanella @Polpetta

**Comment by Polpetta** [comment]
Ok. Anche se secondo me li non ha senso inserire tanta ciccia perché non so quanto è utile sapere in dettaglio che cos'è un campionamento statistico! 😊

**Comment by herrBez** [comment]
Intendevo giusto una frase per togliere l'esempio e lasciare qualcosa che ha senso. Oppure trovare il senso dell'esempio

**Comment by herrBez** [comment]
http://www.pharmtech.com/statistical-solutions-square-root-n-1-sampling-plan

**Comment by Polpetta** [comment]
Boh, io toglierei l'esempio per mettere qualcosa che riassuma brevissimamente. Altrimenti cacciaci una footnote di ignoranza con il link che hai trovato 😁

**Comment by herrBez** [comment]
Ok, allora dopo faccio una pr (come sempre può essere rifiutata!)
