### ISSUE TITLE
Fare una lista puntata dei 4 punti del COBIT

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#16]

**Comment by Polpetta** [comment]
:(

Il 19 lug 2017 17:28, "mzanella" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
È questa @Polpetta?
![image](https://user-images.githubusercontent.com/12596262/29025735-887172b6-7b78-11e7-9f84-82d5885f5d7e.png)

**Comment by Polpetta** [comment]
A quanto pare è stata fatta. Che l'abbia fatta @tfederico?
