### ISSUE TITLE
Capitolo 11 fa parte di 10.2.5

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#162]
**Description**
Il capitolo 11 parla del Security Administrator e basta. Questo non ha senso che sia un capitolo, perché in 10.2.5 si parla delle `Posizioni della Sicurezza` in cui il `Security Administrator` è solamente una misera lista puntata. Secondo me andrebbe mergiato il capitolo in quella parte, e 11.1 bisognerebbe metterlo come una sottosezione di `Posizioni della Sicurezza`, così eliminiamo un capitolo che non ha molto senso.

Che ne pensate @herrBez @mzanella ?

**Comment by herrBez** [comment]
Si sembra avere senso la tua osservazione potrebbe diventare una cosa carina!. Per caso riesci a fare una pr per visualizzarlo?

**Comment by Polpetta** [comment]
Certo, lo faccio più tardi se non è un problema! 😊

**Comment by herrBez** [comment]
SI tranquillo :) Anche io ho scritto una issue che non so se risolverò mai

**Comment by herrBez** [comment]
Ciao, alla fine cosa hai deciso di fare @Polpetta ???

**Comment by Polpetta** [comment]
Mi son dimenticato di fare la PR 😅 finisco di ripassare prima, o la faccio domani mattina! Spero di no ndimenticarmi!

**Comment by herrBez** [comment]
Tranquillo che ti pingo 😂😂
