### ISSUE TITLE
Parti A e B hanno lo stesso nome

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#165]
**Description**
Dobbiamo trovare un altro nome per una delle due parti!

**Comment by herrBez** [comment]
Boh non saprei ho facciamo diventare tutto una parte, anche se non ha molto senso oppure rinominerei la prima come `Business Continuity and disaster recovery` oppure qualcosa tipo i `danni nelle aziende` (ma un po' diverso).
Non so :sweat_smile:

**Comment by Polpetta** [comment]
Non ha senso unirle in quanto l'avevamo staccate precedentemente 😅

Il 19 ago 2017 21:34, "herrBez" <notifications@github.com> ha scritto:

**Comment by Polpetta** [comment]
Il problema è che guardando nelle slide pare che non ci sia un nome in comune per i primi due capitoli...quindi ci tocca inventarci qualcosa 🤔

**Comment by herrBez** [comment]
Cosa accomuna i primi due capitoli? 

Frodi e disaster e recovery. 

Non sono in qualche maniera legata ai `rischi inerenti nelle aziende` ???
