### ISSUE TITLE
Mettere a posto esercizio 7

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#17]

**Comment by herrBez** [comment]
Di seguito elenco quali delle risposte vanno sviluppate ulteriormente:

- [x] Quali sono gli elementi chiave di una frode, e quali tecniche possono essere
utilizzate per contrastare questi elementi chiave? Nella risposta mancano le tecniche per contrastare gli elementi chiave della frode
- [ ] Secondo me vanno sviluppate ulteriormente le considerazioni legali della frode (va a braccietto con l'issue #42 

Se vedete altre criticità aggiungete un commento qui

**Comment by Polpetta** [comment]
Secondo me conviene che fate una PR con le modifiche alla risposta che volete e poi ne discutiamo la altrimenti qui non si va avanti! 😊

**Comment by mzanella** [comment]
@herrBez sulle tecniche per contrastare una frode aggiungerei:
>Una delle prime cose da fare è non sottovalutare la possibile frustazione dei lavoratori: sia di quelli con un alto grado di studio ma messi in lavori di basso livello, sia nel caso in cui un lavoratore per troppo tempo non riceva una promozione. Attenzione deve essere prestata a come la dirigenza si comporta: infatti i lavoratori a livello più basso la prenderà come esempio. Oltre a ciò rispettare la segregation of duties, sicurezza dei beni e dei luoghi, restringendo l'accesso delle aree più critiche e fare background checks dei propri lavoratori, scoprendo in questo modo finti titoli di studio o che dei lavoratori hanno già compiuto delle frodi.

**Comment by mzanella** [comment]
Però non so come sviluppare l'altra parte quella sulle note legali @herrBez. Creo il branche e aggiungo quanto scritto sopra intanto.

**Comment by herrBez** [comment]
Non vorrei avere esagerato, ma questo è più o meno quanto c'è scritto nel libro linkato sotto la slide (ho tagliato qualcosina):


> Dal punto di vista legale una frode consiste nel fornire false informazioni
a qualcuno per fare soldi. Questa azione è intenzionale (dolosa) e causa 
un danno materiale ad una vittima. 
Provare che una frode è avvenuta è molto semplice: infatti
molto spesso è evidente se qualcosa è falso, materiale e se c'è una perdita
per la vittima.
Invece provare il dolo è molto complicato. Infatti, la maggior parte delle
volte la prima difesa in caso di frodi è asserire che si ha commesso un 
errore, il che alcune volte corrisponde a realtà.
Per questo gli investigatori devono cercare prove e indizi
a supporto dell'accusa. Alcuni esempi lampanti sono la manipolazione
di documenti o la distruzione di prove (anche se alcune volte queste
azioni vengono commesse per nascondere il fatto che si ha sbagliato, 
per paura delle conseguenze).
L'intralciare le indagini e mentire agli investigatori
sono altri campanelli d'allarme che fanno aumentare i sospetti.
Inoltre comportamenti
non etici mostrano qualcosa riguardo alle tendenze dell'accusato.
Inoltre è necessario dimostrare che l'accusato ha avuto dei benefici
dall'avvento della frode.
    Nessuno di questi fattori da solo può provare l'intenzionalità oltre
ogni ragionevole dubbio.
In assenza di una confessione dell'accusato, l'intento può essere
stabilito attraverso una lista di campanelli d'allarme.


Se avete suggerimenti di come tagliare ulteriormente/sapete cosa tenere fatemi sapere

**Comment by Polpetta** [comment]
Io quella volta avevo risposto seguendo quanto aveva detto il prof a lezione, poi non so che genere di risposta voglia fargli ma non penso sia fondamentale scrivergli un walltext 😁 

Comunque apparte i `campanelli d'allarme` ripetuti un po' di volte secondo me come risposta va bene così, non aggiungerei altro

**Comment by mzanella** [comment]
A me va bene anche con i campanelli d'allarme perchè suona bene:joy:

**Comment by Polpetta** [comment]
Va bene allora 😁

**Comment by herrBez** [comment]
Ho scritto di getto :smile: . Quindi teniamo la pappardella (un po' rielaborata? cioè sostituendo l'ultimo campanello d'allarme o con segnale d'allarme o con indizi)

**Comment by Polpetta** [comment]
Boh per me va bene anche così

**Comment by herrBez** [comment]
Allora apro un branch le due aggiunte e faccio la pull-request, ok?

**Comment by mzanella** [comment]
C'è già il branch con la prima parte aggiunta

**Comment by mzanella** [comment]
Se vuoi aggiungo tutto io @herrBez

**Comment by herrBez** [comment]
Daghe!
