### ISSUE TITLE
Controlli delle frodi

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#171]
**Description**
I tipi di controlli delle frodi 1.3 secondo le slide sono 3 (preso dal libro essentials of corporate fraud).

I controlli compensativi (presi dal CISA Manual) che abbiamo spostato nella sezione 1.3 vengono messi in atto per contrastare l'assenza di segregation of duties (soprattutto in realtà con pochi dipendenti) e quindi **NON DOVREBBERO FARE PARTE** della sezione 1.3 . Ma dovrebbero essere sotto segregation of duty come nelle slide. 

![image](https://user-images.githubusercontent.com/6976484/29494023-5b8a6d28-85a2-11e7-9992-cd702871d636.png)
![image](https://user-images.githubusercontent.com/6976484/29494027-63d15208-85a2-11e7-8744-ad076ca53bbd.png)

Cosa ne pensate @mzanella @Polpetta 

**Other issues**

**Comment by Polpetta** [comment]
Ok, quindi facciamo un revert di #67?

**Comment by herrBez** [comment]
Non so aspetterei un ACK di @mzanella ,

**Comment by Polpetta** [comment]
Boh io intanto ho fatto la PR poi vedete voi 😅 al massimo la chiudiamo non muore nessuno

**Comment by mzanella** [comment]
Ma quelli di sopra non sono i controlli compensativi per la carenza della segregation of duty? comunque per me è abbastanza indifferente dove li mettiamo :sweat_smile:

**Comment by herrBez** [comment]
Se cerchi nel manuale di ISACA i controlli compensativi trovi questa sezione (e in altri luoghi vengono citatti, ma non so se si riferiscono alla stessa cosa).

In ogni caso nel libro delle frodi vengono citati solo gli altri 3 controlli. 

Quindi in teoria sti controlli compensativi ci sono quando non si riesce a garantiere una segregation of duty fatta bene (persone diverse per Origine Autenticazione Verifica).

Sinceramente però non so.

**Comment by Polpetta** [comment]
Ok, quindi spostiamo?
