### ISSUE TITLE
Network redundancy. Domanda

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#176]
**Description**
Qualcuno mi sa spiegare in parole questa slide?
![image](https://user-images.githubusercontent.com/6976484/29506826-d5c3773c-864d-11e7-947c-8600da0b0cf3.png)
In particolare la differenza tra Alternate Routing e Diverse Routing 
**Other issues**

**Comment by mzanella** [comment]
In teoria la differenza é che sul primo fai tipo un contratto con il tuo
ISP che ti dia Internet tramite un altro mezzo (quelli scritti dopo) mentre
il secondo fai un contratto con un altro ISP

**Comment by Polpetta** [comment]
È spiegato a pagina 18, in 2.4.2

**Comment by herrBez** [comment]
Ok, grazie. sinceramente mi aveva confuso 
![image](https://user-images.githubusercontent.com/6976484/29511325-2d5a627e-865f-11e7-8831-eeaad251cd43.png)
Nel senso società intesa come ISP.
