### ISSUE TITLE
Sistemare sezione modalità di dispiegamento

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#177]
**Description**
Sezione 2.4.4.1
Il modello di deployment ibrido degli appunti non é lo stesso delle slide!

Eliminerei in quella sezione la definizione di multi-tenancy che viene ripresa poco più avanti nella sezione 2.4.4.4
**Other issues**

**Comment by Polpetta** [comment]
Ciao, non sto studiando dalle slide, che dicono riguardo il deployment ibrido?

Comunque è uguale per il \textit{multi-tenancy}, a me non dispiace che prima venga accennato da un punto di vista della sicurezza e poi da uno un po' più del business 😊

**Comment by herrBez** [comment]
![image](https://user-images.githubusercontent.com/6976484/29510220-4dde039c-865b-11e7-9b93-9308d54ce7f5.png)

Comunque in teoria la sezione dopo parla delle preoccupazioni legate alla sicurezza. Pensavo di spostare tutte le considerazioni di sicurezza di 2.4.4.1 in 2.4.4.4 rendendo cosí quella sezione.

Potri fare una PR per quest'ultimo punto perchè non c'entra con la prima parte

**Comment by Polpetta** [comment]
Ok. Comunque riguardo l'hybrid cloud forse c'è solo da aggiungere che potrebbero usare tecnologie proprietarie standardizzate (ma ha senso?)

**Comment by herrBez** [comment]
Il fatto importante che non emerge negli appunti è che quando si parla di ibrido non si usa un solo cloud ma due cloud in comunicazione. Questi cloud possono essere di diversi tipi (anche comunitario-pubblico) ma comunque possono comunicare.

Attualmente diciamo mistro tra public e private che non mi sembra la stessa cosa

**Comment by Polpetta** [comment]
ok allora è da aggiungere quello 😅
