### ISSUE TITLE
Mistranslation di SAAS

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#178]
**Description**
Negli appunti 
![image](https://user-images.githubusercontent.com/6976484/29508205-e902939a-8653-11e7-921f-e203577a3534.png)
Mentre nelle slide
![image](https://user-images.githubusercontent.com/6976484/29508212-f37cfe5a-8653-11e7-8527-5cd8d97df54d.png)
Il providere fa girare le SUE applicazioni non le terze parti

Inoltre in PaaS userei il cliente/azienda invece del `ci faccio`
**Other issues**

**Comment by Polpetta** [comment]
Va bene 👍
