### ISSUE TITLE
Proposta di merge di contenuto + Retaggio di sezione

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#179]
**Description**
La sezione 2.4.4.5 non dovrebbe (secondo) me fare parte del cloud ma dovrebbe essere integrata nella sezione 2.4.3. Inoltre c'è una slide che fornisce dettagli su hot site. Questa la integrerei sempre nella sezione 2.4.3.
Infine darei alla sezione 2.4.5 la dignità di una section perchè non c'entra con le tipologie di disaster recovery ma è più una cosa a se stante che chiude e riassume un po' tutto il discorso precedentemente fatto.
**Other issues**

**Comment by Polpetta** [comment]
Boh per gli hot site mi pare abbastanza chiaro non scriverei di più.

Per il merge del reciprocal agreement va bene, anche l'elevazione del BCP a section è ok basta che sposti la subsection sugli esercizi prima del BCP.
