### ISSUE TITLE
Mistranslation

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#181]
**Description**
Tipologie di test per la Business continuity sezione 2.5.4.1:
![image](https://user-images.githubusercontent.com/6976484/29511793-85bba4ea-8660-11e7-9f80-5db7e47c4669.png)
contro:
![image](https://user-images.githubusercontent.com/6976484/29511816-9883d624-8660-11e7-8e64-394b1d048a73.png)

e
![image](https://user-images.githubusercontent.com/6976484/29511825-a05e18fa-8660-11e7-8d21-026369611027.png)
contro:
![image](https://user-images.githubusercontent.com/6976484/29511840-aa6323ea-8660-11e7-9822-a015325fd44e.png)
quest'ultima forse va già bene ma la prima è un po' diversa almeno secondo me. Io la tradurrei
come 

> verifica che il piano copra tutti gli aspetti importanti.

In ogni caso non esiste il "piano di copertura" inoltre la domanda non é se tutti i piani importanti sono coperti ma se tutti gli aspetti importanti sono coperti.

Scusate per la pignoleria!
**Other issues**

**Comment by Polpetta** [comment]
Va bene, traduci pure 😊  Pusha in develop che non penso serva una pr per sta cosa 😅
