### ISSUE TITLE
Completare il pargrafo sui passi del test.

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#182]
**Description**
Completare la sezione sui passi del test
**APPUNTI**
![image](https://user-images.githubusercontent.com/6976484/29512052-73ce808a-8661-11e7-9d3e-cb65dfb89d1e.png)
**SLIDE**
![image](https://user-images.githubusercontent.com/6976484/29512066-7e681c7c-8661-11e7-8224-43917ba87550.png)

Farei emergere (almeno) all'interno della sezione i nomi PreTest, Test e PostTest, non si sa mai che li chieda all'esame ^^
**Other issues**

**Comment by Polpetta** [comment]
Qui nessuno aveva voglia di scrivere durante lezione evidentemente 😅

**Comment by herrBez** [comment]
Me compreso xD. Cerco di provvedere :)
