### ISSUE TITLE
Mancano degli esercizi + Esercizi nella sezione sbagliata!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#183]
**Description**
Mentre mancano i seguenti esercizi sul test al disaster e recovery plan!!!

1. 
![image](https://user-images.githubusercontent.com/6976484/29512671-20405b94-8663-11e7-9782-c4bd6507bd3d.png)
2. 
![image](https://user-images.githubusercontent.com/6976484/29512674-2836ca5e-8663-11e7-857d-6aee40f6d29d.png)
3.
 ![image](https://user-images.githubusercontent.com/6976484/29512690-377fc510-8663-11e7-9dd6-37bf3c55b503.png)
4.
 ![image](https://user-images.githubusercontent.com/6976484/29512701-4230b3c0-8663-11e7-9076-8adfbb7999ba.png)
5.
![image](https://user-images.githubusercontent.com/6976484/29512713-4d281eb2-8663-11e7-8b9f-2813c5e510be.png)

Inoltre creerei una nuova sezione per gli esercizi del capitolo 3 perchè fanno parte di due **PARTI** diverse e quindi non dovrebbero trovarsi nel capitolo 18 degli esercizi!!!!

**Other issues**

**Comment by Polpetta** [comment]
Se non ci sono questi esercizi significa che non sono stati visti a lezione. Ho partecipato a tutte le lezioni e comunque eravamo sempre i 3 😅 

Crea pure la nuova sezione in ogni caso, basta che metti i ref come ho fatto per tutti gli altri esercizi...

---


In ogni caso la seconda domanda è la 1 per forza (la vita delle persone prima di tutto), e la terza domanda metterei la 1.
L'ultima di testare siti alternativi, per vedere se ottengo risultati uguali potrei eseguire un `parallel test` in cui gli butto le stesse transazioni che ho appena ottenuto dal sito in produzione e vedo se quello alternativo fornisce gli stessi risultati senza interrompere il mio servizio, quindi sarei per la 2.

Le altre non sono sicuro 😅

**Comment by mzanella** [comment]
Sono d'accordo con @Polpetta per le risposte...

**Comment by herrBez** [comment]
Sembra strano anche a me che non le abbiamo analizzate, ma non ci costa niente metterle dentro al documento. Più che altro non vorrei che dopo le mettesse all'esame


Allora ho aggiunto i numeri 
Per me larisposta alle 2 è la vita umana su cui non ci piove.
Risposta 5 sono d'accordo con voi.

3. Business Impact analysis 

4 direi o 2 o 3 escludendo le altre

Mentre per la 1 non so: dice la PRIMA e più importante operazione e nelle slide e gli appunti si dice 
![image](https://user-images.githubusercontent.com/6976484/29514013-57feabfe-8667-11e7-97c3-7e349d263e52.png)

soprattutto in quest'ordine sembra fare capire che sia quella, ma non sono sicuro

**Comment by herrBez** [comment]
Faccio una PR. Direi di chiuderla e aprire una issue per discutere le risposte mancanti con un'eventuale label prof.
