### ISSUE TITLE
Mistranslation--low priority

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#186]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29529406-d72eeaaa-869f-11e7-8518-f8437e1c20de.png)
contro:
![image](https://user-images.githubusercontent.com/6976484/29529427-eaf49724-869f-11e7-81d3-0c077a7d7596.png)

Io la tradurrei come
> All'interno del BIA sono definiti RPO/RTO per tutti i servizi?
**Other issues**

**Comment by mzanella** [comment]
Top

**Comment by Polpetta** [comment]
Correggi pure 👍
