### ISSUE TITLE
Missing slide

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#187]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29555848-35c9e19e-8724-11e7-9a3c-199e44c699c3.png)

[BC]Manca_Una_Slide(Scusate_gli_underscore_ma_mi_è_andata_in_mona_la_barra_spaziatrice_xD)
La_aggiungiamo_?
**Other issues**

**Comment by Polpetta** [comment]
Sembra comoda anche se non fondamentale! Se hai voglia aggiungila pure come immagine, pusha direttamente che non penso serva un pull request 😅 Basta che poi chiudi la issue 😁  (lo puoi fare direttamente da commit scrivendo tipo `Fix #187 - ....`)

**Comment by herrBez** [comment]
Ma dove la inserisco? Va bene se la metto subito dopo RAID sempre come subsubsection? (Cosí riflette la struttura del riassunto finale)

**Comment by Polpetta** [comment]
Va bene. Siccome non è legata troppo al contenuto (ma più al contesto) ti conviene metterla come `top` quando fai begin figure e mettere una didascalia che la spiega (per top intendo:
```tex
\begin{figure}[t]
...
\end{figure}
```
)

Così rimarrà in alto nella prima pagina con spazio disponibile
