### ISSUE TITLE
possibile errore nelle slide

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#190]
**Description**
Prendo la slide sulla gestione del rischio di Di Pietro:
![image](https://user-images.githubusercontent.com/6976484/29561647-82b9688c-8736-11e7-87e3-913885a217c9.png)
In internet ho trovato questa slide
![image](https://user-images.githubusercontent.com/6976484/29561886-790acdb6-8737-11e7-82c2-928b20249c34.png)
presa da queste [slide](http://slideplayer.com/slide/4449657/) che sono identiche a quelle del prof.

Più che altro non si capisce da dove il professore abbia tirato fuori "Privileged" nelle sue slide.

Questa slide sembra spiegare anche perchè Privileged abbia meno sicurezza delle altre informazioni. 

**DISCLAIMER** qui confidential e in generale la sensitivity classification sembra diversa la classificazione usata:
![image](https://user-images.githubusercontent.com/6976484/29561973-d39019ee-8737-11e7-8c11-fec8f23b9bd5.png)
Contro la nostra : 
![image](https://user-images.githubusercontent.com/6976484/29561999-e5883794-8737-11e7-9ca3-9458f8d2913d.png)

**Other issues**

**Comment by herrBez** [comment]
Inoltre se guardate su [google image](https://www.google.it/search?biw=1301&bih=678&tbm=isch&sa=1&q=handling+of+sensitive+data&oq=handling+of+sensitive+data&gs_l=psy-ab.3...0.0.0.1144906.0.0.0.0.0.0.0.0..0.0....0...1..64.psy-ab..0.0.0.NOj4NHZuLQM#imgrc=R2zrqC2vvF48NM:) potete trovare questa immagine:
![image](https://user-images.githubusercontent.com/6976484/29562281-eb97eff2-8738-11e7-8794-ae8397a541ca.png)
ma poi se cliccate il link andate al link di prima
:male_detective:

**Comment by Polpetta** [comment]
Non ho capito quale sia il problema, è solo la scritta public/privileged? 🤔

**Comment by herrBez** [comment]
Si il problema è quello. Infatti privileged non esiste da nessuna parte e poi magicamente compare SOLO in quella slide e non è coerente con quanto viene prima. Infatti privileged dopo è stato definito a lezione (ma secondo me andrebbe cavato qualsiasi riferimento a privileged) perchè il grado massimo che abbiamo negli appunti è confidential e non si è mai sentito privileged.

**Comment by Polpetta** [comment]
Beh sappiamo che è un errore del prof e che è da tenere in considerazione, ma non mi metto a modificare con GIMP lo screen della tabella 🙅‍♂️

**Comment by herrBez** [comment]
No, ma toglierei il testo che spiega di privileged. Crea solo confusione. A parte che puoi prendere qui l'immagine corretta 😅

**Comment by Polpetta** [comment]
Mi dici il titolo della sezione o comunque dove si trova? Che così faccio un Ctrl-F rapido e cambio in due secondi altrimenti impazzisco a cercarla

**Comment by herrBez** [comment]
Capitolo: 3.5.3
File: 15-Les150317.tex
