### ISSUE TITLE
Missing Question

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#191]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29568510-d6782048-8750-11e7-9d36-6d601784ac81.png)
Per_me_è_la_3,ma_sono_un_po_in_dubbio_con_la_2...
**Other issues**

**Comment by Polpetta** [comment]
Dipende da cosa:
2 - Se si sta parlando di dati (e quindi ci sta che il proprietario decida chi ha accesso ai suoi dati)
3 - Se si sta parlando di autorizzazioni più generiche come gli account o l'accesso a determinati servizi informatici

---

4 - Non ha tanto senso ma la metterei nel caso stessimo parlando anche di accessi ad aree fisiche, non solo a livello informatico.

**Comment by herrBez** [comment]
Non vorrei dire ma anche 1 avrebbe il suo perchè:
![image](https://user-images.githubusercontent.com/6976484/29626174-3ae38ac6-882e-11e7-83da-461fcda6c6c0.png)

Comunque non si parla di accessi ma permessi intesi come read write execute (rwx) al sistema informatico e quindi di dati. Escluderei pertanto la 4

**Comment by herrBez** [comment]
Si anche io adesso che ci penso sarei più per 2. Provo a chiedere nel gruppo SRM? ( Ci sarà qualche anima pia che ci risponderà)

**Comment by Polpetta** [comment]
Boh però son andato a rileggermi le definizioni e boh mi son spostato un
poco verso la 3... Tipo 60/40 :/

Il 23 ago 2017 21:30, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si perchè parla di permessi e non di accesso ai file sembra una casa più generale. Potrebbe essere in effetti .

**Comment by Polpetta** [comment]
Io voto per la 3.

**Comment by herrBez** [comment]
Abbiamo avuto conferma per la 3. Ora aspettiamo il prof.

**Comment by herrBez** [comment]
> e' il data owner; il security admin implementa a livello tecnico le indicazioni del data owner.


E invece è la due, :sweat_smile:  (almeno la mia intuizione iniziale non era sbagliata, anche se mi ero ricreduto). Prenderei la due  anche perchè `verba volant, scripta manent`

**Comment by mzanella** [comment]
Non so dove aggiungerla:sweat_smile: @herrBez su che pacco di slide era?

**Comment by herrBez** [comment]
Bella domanda :sob: dopo cerco di aggiungerla io con la footnote del professore ^^

**Comment by mzanella** [comment]
Ok senno se avevi almeno una idea facevo io:sweat_smile:
