### ISSUE TITLE
Dovremmo Mergiare 4.2 e 4.3?

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#192]
**Description**
Secondo_me_il-capitolo-4.2-e-il-capitolo-4.3-dovrebbero-essere-fusi-perchè-parlano-della-stessa-cosa.O-almeno-il-bell-la-padula-dovrebbe-stare-sotto-il-capitolo4.2
**Other issues**

**Comment by herrBez** [comment]
Per_intenderci:
![image](https://user-images.githubusercontent.com/6976484/29569729-b102e52e-8754-11e7-9ea9-3e6bd1f289fe.png)

**Comment by herrBez** [comment]
Inoltre_la_declassificazione_sembrerebbe_essere_diversa_da_quella_messa_negli_appnti.Anche_se_quella_degli_appunti_ha_MOLTO-più_senso

**Comment by Polpetta** [comment]
Quella degli appunti l'ha detta il prof.

In ogni caso non so, BLP la si usa anche al di fuori dell'ambito militare e secondo me ci sta che stia un po' a parte. Certo è stato progettato inizialmente per l'ambito militare però non esclude che possa essere utilizzato anche per altro

**Comment by herrBez** [comment]
Secondo me sono correlate perchè se guardi la seconda slide fa riferimento alla prima (anche per la classificazione! Top Secret. Secret, Confidential e non-classified. E inoltre la confidential property si riferisce con ogni probabilità al BLP. 

Per me andrebbero fuse (ma aggiungerei se non c'è già che il BLP viene oggi usato anche al di fuori del'ambito militare per le sue proprietà desiderabili)

**Comment by Polpetta** [comment]
Cambia allora la section del BLP e mettila come subsection (o insomma rendila sottoparte dell'altra sezione). Se vedi che ha senso pushala pure chiudendo sta issue
