### ISSUE TITLE
12.2 e 12.4 hanno lo stesso titolo

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#193]
**Description**
Boh forse bisognerebbe cambiare uno dei due con qualcosa di più significativo

**Other issues**

**Comment by mzanella** [comment]
e se mergiamo le due parti @Polpetta ?

**Comment by herrBez** [comment]
E' così perchè nelle slide è così @Polpetta prova a darci un'occhiata e decidere se mergiare o meno (a me piacerebbe si mergiasse ^^)

**Comment by Polpetta** [comment]
Si potrebbe mergiare sotto un unico titolo, però manterrei i contenuti delle due parti separate (in quanto se non ricordo male non si ripetono i contenuti, solo i titoli)! 😊

**Comment by herrBez** [comment]
Ribadisco sono gli attuali capitolo 11.2 e 11.4 e non 12.2 e 12.4

**Comment by Polpetta** [comment]
Va che stai facendo un po' casino perché non è possibile 😅 
![image](https://user-images.githubusercontent.com/5928183/30152112-656afcf4-93b2-11e7-8873-676f3398c5b4.png)

**Comment by Polpetta** [comment]
Ok fermi tutti, ho capito cos'è successo.

Ho fatto una capellata, @herrBez grazie per la segnalazione. Non so perché ma ho fatto una cosa diversa da quanto richiesto nella issue (son mona forte eh).
Ora faccio il revert del commit e rinomino la sezione, così rimettiamo tutto in ordine.

**Comment by herrBez** [comment]
Spiegami un attimo xD. Cosa sta succedendo?

**Comment by Polpetta** [comment]
Nel capitolo 12 se vedi il branch `develop` c'è una ripetizione di titoli fatalità nella parte 12.2 e 12.2.2. Probabilmente distrattamente ho messo a posto quella parte e **non** la ripetizione presente nel capitolo 11 (che però prima era capitolo 12). Quindi è venuto fuori un casino con la nomenclatura. Ora metto a posto e aggiorno la pull request!

**Comment by herrBez** [comment]
Si il problema era la roba "Relazione insicura tra componenti"

**Comment by Polpetta** [comment]
Si, ma questo è già stato fatto nella pull request #250, non so perché @mzanella abbia risolto più problemi contemporaneamente senza fare le cose atomicamente 😅 Quindi il problema è già stato risolto. Penso possiamo chiudere questa issue come risolta, e l'altra pull request dove ho messo a posto comunque un problema nel _vero_ capitolo 12 collegarla ad un'altra issue che ora apro.

Ok?

**Comment by herrBez** [comment]
Si. Lasciamoci questa storia alle spalle xD
