### ISSUE TITLE
NIDS mancante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#194]
**Description**
Nelle slide oltre a parlare dell'HIDS si parla anche di NIDS nella sezione 5.4.4 .

![image](https://user-images.githubusercontent.com/6976484/29622231-275fb566-8823-11e7-8c18-3c2124585288.png)

Appena mi riparano il PC cerco di rimediare
**Other issues**

**Comment by herrBez** [comment]
Inoltre non si capisce attualmente il perchè nel titolo ci sia IPS se poi non viene spiegato nel testo.

**Comment by Polpetta** [comment]
Ho visto anche io riguardo il NIDS, non so bene cosa sia, suppongo che quella N stia per `Neural`?

IPS comunque è `Intrusion Prevention System` è spiegato negli appunti! 😊

**Comment by herrBez** [comment]
N sta per network come puoi ben vedere dallo screen shot 😅 

Ma di IPS non emerge che si fanno passare i pacchetti tramite l?IPS

**Comment by Polpetta** [comment]
Hahaha cazzo non avevo manco visto, scusa 😁 

> Ma di IPS non emerge che si fanno passare i pacchetti tramite l?IPS

?

**Comment by herrBez** [comment]
Guarda la slide! 

> IPS = Packets are routed through IPS
