### ISSUE TITLE
Honeypot vs Honeynet non chiarissimo

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#195]
**Description**
La sezione sulle honeynet e honeypot degli appunti non è chiarissima e non corrisponde alle slide:

![image](https://user-images.githubusercontent.com/6976484/29624024-65b4c284-8828-11e7-974c-3ffffdb00b96.png)

Alla fine per **entrambe** vale l'elenco puntato!!!
**Other issues**

**Comment by Polpetta** [comment]
Ho letto anche io ieri sera, e son confuso, perché non so se fidarmi di quello che ha detto il prof o di quello che c'è scritto nelle slide 😅 Però se ci pensi bene entrambe le definizioni (del prof e slide) alla fine puntano alla stessa cosa: sono account/zone di rete rese appetibili apposta per l'attaccante in maniera tale da studiarne i suoi comportamenti o da evitare attacchi ai sistemi reali.

**Comment by herrBez** [comment]
Da come nelle slide:
Honeypot è un sistema singolo (Computer?)
Honeynet è una rete intera

Ma alla fine sono dei "fake" per carpire informazioni  sugli attaccanti e tutte le robe la.

**Comment by Polpetta** [comment]
Yessss
