### ISSUE TITLE
Bisogno di chiarimento

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#196]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29626005-b6484e64-882d-11e7-97e9-e74839538b4d.png)

Non è chiaro:

cosa sia la firma (la formuletta)
**Other issues**

**Comment by Polpetta** [comment]
Mancano di sicuro delle informazioni a quella formula (che secondo me non è la firma). Si potrebbe tenere quella sopra che è abbastanza riassuntiva ed eliminare quella sotto che fa solo confusione.

**Comment by herrBez** [comment]
Si toglierei la firma è e la seconda formula.
