### ISSUE TITLE
Mistraslation

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#197]
**Description**
*Slide:*
![image](https://user-images.githubusercontent.com/6976484/29633607-27713146-8847-11e7-87fa-592aa55ba807.png)
*Appunti*
![image](https://user-images.githubusercontent.com/6976484/29633638-4175d178-8847-11e7-9075-ee2a6322bf96.png)

Penso che:
`Governance and Security Management: allocano risorse, valutano e usano i
risultati della valutazione del rischio;` si intendesse **SENIOR** management 

Inoltre aggiungerei il ruolo di CIO e CISO rispetto al RISK management, perché non è scontatissimo.

**Other issues**

**Comment by Polpetta** [comment]
Si, è sicuramente `senior`.

Che cosa diresti del CISO e CSO?

**Comment by herrBez** [comment]
A parte che rileggendo oggi non si parla di CIO ma di Information Security Manager.

Comunque direi solo quanto scritto

`Information Securitz manager: svilupa, collabora gestisce i rischi legato al processo di IS risk management.` 

Mentre per il CIO non saprei... Si occupa del budget .. e devo guardare nel CISA manual.

**Comment by Polpetta** [comment]
Quindi:
- Rimuoviamo CIO e CISO e ci mettiamo l'information security manager
- Cambio security in senior in Governance and Security Manager

Se mi dici pusho ste robe dirette e chiudo la issue

**Comment by herrBez** [comment]
ASpetta il CIO c'è non c'è il CISO

**Comment by Polpetta** [comment]
Lo so che non lo sono, ma dimmi cosa devo correggere o correggilo te perché non ci sto capendo niente e voglio mettere apposto sta roba in meno tempo possibile 😂

**Comment by herrBez** [comment]
Scusa ma dammi tempo fino a pranzo e poi sistemo. Scusa ^^ è difificle eseguire i commit su github (non riesco mai a trovare il file giusto!!!)

**Comment by Polpetta** [comment]
Lo so, se vuoi trovare stringhe di testo all'interno del documento sorgente usa questo codice in bash:
```sh
for i in res/sections/*.tex
do
echo "-- $i --"
cat $i | grep "TESTO DA CERCARE"
done

```

**Comment by herrBez** [comment]
Peccato stia usando Winzozz 10 ... (Sto ancora aspettando il PC)

**Comment by Polpetta** [comment]
Git per windows ha la bash integrata ;)

**Comment by herrBez** [comment]
Sto usando chrome.. adesso provo a vedere.

**Comment by Polpetta** [comment]
Ma quindi come pushi?🤔

**Comment by herrBez** [comment]
Direttamente sul browser. FUCK YEAH
