### ISSUE TITLE
Duplicazione

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#20]
**Description**
- [x] Sezione 2.5.5 e paragrafo 2.5.5.2 sembrano uguali
- [x] Sezioni 4.6.3 e 4.6.5 molto simili
- [x] Figura 6.2 e 6.4 sono uguali
- [x] Sezione 7.5.5.1 Tipologie di controllo spiegate sia nell'elenco che appena sotto
- [x] Sezioni da 9.1.1.6.1 a 9.1.1.6.6 uguali alle sezioni da 9.0.0.0.1 a 9.0.0.0.6

**Comment by Polpetta** [comment]
Alcune immagini sono state appositamente ripetute da @tfederico

**Comment by mzanella** [comment]
Se, a parte le immagini che le lascio così, mi date un riscontro sistemo

**Comment by Polpetta** [comment]
Riesci a rompere questa lista in più issue e a vedere se alcuni punti sono stati fatti?

**Comment by mzanella** [comment]
Se mi mettete le spunte dove effettivamente abbiamo un bug io posso lavorare sulle varie issue che ne vengono fuori!

**Comment by Polpetta** [comment]
Intanto rompi queste, poi quando hai fatto chiudila che non serve più e poi per ogni problema faremo una issue senza troppe liste o diventano troppo grandi e nessuno se le caga più
