### ISSUE TITLE
Slide mancante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#200]
**Description**
Mi sembra che manchino i contenuti di questa slide:
![image](https://user-images.githubusercontent.com/6976484/29638477-aa5dca82-8857-11e7-949d-d4674f01e767.png)

Non secondo voi avrebbe senso aggiungerli?

#200 🎉 
**Other issues**

**Comment by Polpetta** [comment]
Non so. Mettiamo uno screen dello schemino?

**Comment by herrBez** [comment]
Boh...

**Comment by Polpetta** [comment]
Lo aggiungo e lo pusho diretto, amen, meglio qualcosa in più che qualcosa in meno

**Comment by herrBez** [comment]
Daghe!
