### ISSUE TITLE
Risposta mancante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#201]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29654029-d8a93b0c-88ab-11e7-8349-1f503dc2c099.png)

**Other issues**

**Comment by herrBez** [comment]
Per me è senza ombra di dubbio la 4. perchè chiede il **PRIMO** e più importante test da eseguire.
![image](https://user-images.githubusercontent.com/6976484/29656991-87395c74-88b6-11e7-8803-5880c37eb35f.png)
Inoltre ho letto nel CISA review manual che Full operational dipende da Preparedness e Desk-based e Preparedness dipende da desk-based.

Quindi senza desk-based non si potrebbero avere gli altri

**Comment by herrBez** [comment]
@mzanella @Polpetta convince anche voi?

**Comment by Polpetta** [comment]
Sisi, è senza dubbio la 4.

**Comment by Polpetta** [comment]
Pusha diretto la soluzione senza PR, metti `Fix #201 - ...` come testo del commit così sta issue si chiude da sola

**Comment by herrBez** [comment]
@Polpetta . Riesci a fixarlo?
