### ISSUE TITLE
Definizione di IS audit (troppo implicita)

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#203]
**Description**
Appunti:
![image](https://user-images.githubusercontent.com/6976484/29657761-f1da02e8-88b8-11e7-83da-e95ea9ad12f0.png)

Nel capitolo  7.2 non emerge (secondo me) a sufficienza il fatto che l'IS AUDIT si occupa del sistema di information processing come ben evidenziato nelle slide:
![image](https://user-images.githubusercontent.com/6976484/29657774-fd1ce3be-88b8-11e7-90da-b575f8a9724e.png)

**Other issues**

**Comment by Polpetta** [comment]
E che proponi di fare? 😊

**Comment by herrBez** [comment]
Proporrei di aggiungere questa definizione quando parliamo di IS audit nel capitolo relativo ai tipi di audit.

**Comment by Polpetta** [comment]
Va bene!

Il 24 ago 2017 16:18, "herrBez" <notifications@github.com> ha scritto:
