### ISSUE TITLE
Definizione di Annualized Rate of Occurrence

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#21]
**Description**
Nella sezione 6.3.1.4 _Annualized Rate of Occurrence_ è spiegato in questo modo _quanto costa questo evento in un anno?_ ma subito dopo viene introdotto _Annual Loss Expectancy_ spiegato come _la perdita attesa annuale_ che mi sembra la stessa cosa, il problema è che uno viene calcolato in funzione dell'altro. L'_Annualized Rate of Occurrence_ non potrebbe essere quante volte un evento può capitare in un anno?

**Comment by Polpetta** [comment]
Questo è quello che il prof ha scritto in merito nelle sue slide:

![image](https://user-images.githubusercontent.com/5928183/28962667-ae852688-7906-11e7-891a-9f3db5b52e41.png)

Quindi si hai ragione, l'ARO è descritto in maniera erronea. Con `quanto costa questo evento in un anno?` probabilmente si voleva intendere una cosa del tipo `quanto è il costo distribuito dell'asset durante gli anni prima che accada un disastro?` (probabilmente spiegarlo come una domanda non è stata un'idea buona dato che non è chiaro esprimerlo neanche così 😅)
