### ISSUE TITLE
Errore di traduzione????

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#210]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29669930-5b704024-88e5-11e7-932e-6821556b2780.png)
è stato tradotto incosì:
![image](https://user-images.githubusercontent.com/6976484/29669949-690c516e-88e5-11e7-8a31-1c83ff4dec77.png)

Secondo me sarebbe stato più corretto:

> Auto-valutazione dei controlli 

e non

> Controlli dell'auto-valutazione

Non sono sicuro al 100%
**Other issues**

**Comment by Polpetta** [comment]
Boh non saprei

**Comment by herrBez** [comment]
@mzanella 

Secondo me è anche più coerenti con i contenuti del capitoloetto che dice che si usa un audit interno per verificare i controlli

**Comment by herrBez** [comment]
@mzanella

**Comment by mzanella** [comment]
Sono d'accordo con @herrBez
