### ISSUE TITLE
Aggiungere riferimento all'immagine

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#211]
**Description**
Aggiungere un riferimento all'immagine 7.5 nel capitoletto 7.5.7.2
**Other issues**

**Comment by Polpetta** [comment]
Non esiste 7.5.7.2 🤔

**Comment by herrBez** [comment]
Ok nella versione 0.20 si, ma nel pdf attuale dovrebbe essere 7.4.7.2

**Comment by Polpetta** [comment]
Dici questa immagine?
![image](https://user-images.githubusercontent.com/5928183/29705959-7f43cfde-8980-11e7-8561-e0c8b4706578.png)

**Comment by herrBez** [comment]
(dovete scusarmi non ho più compilato i pdf sto usando il fisso... ) Si o in alternativa si potrebbe eliminare l'immagine e mergiare i contenuti dell'immagine nel testo (che mi sembrano riportabili in forma testuale) e più sostanziosi del contenuto attuale del capitoletto.

**Comment by Polpetta** [comment]
Ma a me pareva che spiegasse bene l'immagine 😅 Non so poi mi ha chiarito le idee a me 😁

**Comment by herrBez** [comment]
Si anche a me fonderei i contenuti dell'immagine nel testo o aggiungerei un riferimento (p.es. nella versione 0.20 l?immagine è nella pagina dopo) e non si capisce subito a che si riferisce.

**Comment by Polpetta** [comment]
Se vuoi puoi fare una pr? Così vediamo come viene
