### ISSUE TITLE
Blank Pages un po' a caso?

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#212]
**Description**
Non capisco quale sia il criterio per cui si lascia una pagina vuota: per esempio (prendo la versione 0.20:

- Pagina 91 viene lasciata bianca per la prossima parte (presumo)
- Dopo pagina 100 non viene lasciata una pagina bianca (e dopo inizia una parte) 

Anche nei capitoli degli esercizi non è chiarissimo, per esempio:
 - pagina 183 viene lasciata una pagina bianca
- dopo pagina 176 ci sono subito gli esercizi.

Sarebbe carino uniformare le cose. (Comunque ci sono altri esempi..). 
**Other issues**

**Comment by Polpetta** [comment]
Sono uniformi. Il documento è in [openright](https://texblog.org/2013/02/13/latex-documentclass-options-illustrated/#openright), i capitoli aprono sempre nella prima facciata di destra.

**Comment by herrBez** [comment]
Ok. Leggendolo così sembravano irregolari. Non so allora teniamo così. Scusa

**Comment by Polpetta** [comment]
No problem 😊
