### ISSUE TITLE
Titolo del Capitolo 8

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#213]
**Description**
Io cambierei il titolo del capitolo 8 in sicurezza fisica e del personale. 
E farei una sezione Difesa in Profondità... 
**Other issues**

**Comment by Polpetta** [comment]
Quindi la sicurezza fisica e del personale fa parte del risk management dici?

**Comment by herrBez** [comment]
No  dico che il capitolo 8 si dovrebbe chiamare Sicurezza fisica e del personale non difesa in profondità che è una implementazione\buona pratica della sicurezza fisica.
Secondo me con questo titolo si confondono le carte (almeno a me)

**Comment by Polpetta** [comment]
Ok, ma quindi avrebbe lo stesso nome della parte! A sto punto ha senso tenere la parte?

**Comment by herrBez** [comment]
Bella domanda. Ma non so se faccia realmente parte della parte (scusa il giuoco di parole) precedente. 

RIschio e Sicurezza fisica si centrano ma fino ad un certo punto

**Comment by Polpetta** [comment]
Eh è un casino

**Comment by herrBez** [comment]
Io cambierei solo il titolo del capitolo perchè difesa in profondità è una parte della sicurezza fisica..

**Comment by herrBez** [comment]
e lascierei il discorso sulla parte ad un'altra ISSUE.

**Comment by Polpetta** [comment]
Fatto, fai l'altra issue che lasceremo ai posteri

**Comment by herrBez** [comment]
Ok
