### ISSUE TITLE
Manca del contenuto

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#214]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29678711-e08752a6-88ff-11e7-858e-07674896b616.png)
contro il nostro capitolo 
![image](https://user-images.githubusercontent.com/6976484/29678733-ede09ebc-88ff-11e7-89db-9cc612c06c9b.png)

Inoltre aggiungerei una spiegazione di una riga sull'IPF che vine spiegato in una nota a piè di pagina a capitolo 2.
**Other issues**

**Comment by Polpetta** [comment]
Il 8.2.3 è quello che aveva detto il prof, non abbiamo preso niente dalle slide. Quindi se ritieni opportuno puoi aggiungere qualcosa! 😊 
Anche la footnote sembra una bella idea. Pusha direttamente in `develop` chiudendo la issue qui, non penso sta cosa abbia bisogno di revisione 😅
