### ISSUE TITLE
Mergiare CMM 9.1 e 9.2.1.5 

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#218]
**Description**
Secondo me il capitolo 9.1 andrebbe scritto dove ora c'è il 9.2.1.5 come nelle slide. Infatti secondo me le slide in cui si spiegano i vari livellicorrispondo alle spiegazioni dei diversi livelli (almeno da come interpreto io le slide sul Security MGMT) definiti nella slide sul CMM.

Infatti quelli citati sarebbe i livelli di maturità dei progetti del COBIT 4.1 

**Other issues**

**Comment by Polpetta** [comment]
Si, andrebbe spostato. Effettivamente nelle slide risulta molto più chiara. Mi sa che c'è anche una ripetizioni perché le due liste dicono la stessa cosa alla fine.

**Comment by herrBez** [comment]
Si è un lavoro un po' grosso non credo di riuscire a farlo tanto presto

**Comment by Polpetta** [comment]
Penso che sia una cosa da posteri

**Comment by herrBez** [comment]
O da me tra una settimana se mi va male l'esame 😢

**Comment by Polpetta** [comment]
Speriamo di no! 😁
