### ISSUE TITLE
Sezione 7.5.6 "Evidenza"

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#22]
**Description**
Nella sezione 7.5.6 viene utilizzato più volte il termine _evidenza_. È usato di proposito o come traduzione di _evidence_? in questo caso o sostituirei _evidenza_ con _prova_ oppure terrei il termine in inglese.

**Comment by Polpetta** [comment]
È quello che diceva il prof. Se pensi che un sinonimo li ci starebbe pushalo pure

**Comment by mzanella** [comment]
No se usava questo termine il prof meglio lasciare così anche se mi sembra brutto
