### ISSUE TITLE
Possibile traduzione sbagliata

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#220]
**Description**
Capitolo 9.1.4
Appunti:
![image](https://user-images.githubusercontent.com/6976484/29707109-649877d0-8984-11e7-8a8c-90ac320f4d4a.png)
Slide:
![image](https://user-images.githubusercontent.com/6976484/29707116-715d2a56-8984-11e7-8874-d7495d7fe527.png)

Non dovrebbe essere 

> Documentazione delle Policy
??? 
**Other issues**

**Comment by Polpetta** [comment]
Si, è definitivamente un errore! Pusha diretto in develop chiudendo questa issue, la tua traduzione è corretta

**Comment by herrBez** [comment]
Chiusa per via del commit e10ed9ccbf2ed0c4f316b26c09f09fa0531a09f8 ho sbagliato riferimento nel commento del commit
