### ISSUE TITLE
Criterio Capitolo esercizi

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#221]
**Description**
Con quale criterio si usa un capitolo di esercizi?

Ogni tanto si fa un capitolo di esercizi per una parte interna, invece alle volte un singolo capitolo. 

Esempio: La parte sul risk management ha due capitoli dedicati: Capitolo 22. Capitolo 21
mentre il capitolo 24 è dedicato a tutta la parte relativa ai controlli. 
**Other issues**

**Comment by Polpetta** [comment]
È tutto scalato di uno. Siccome volevo solo una parte per gli esercizi, nella sezione esercizi le parti della teoria son diventate capitoli, i capitoli sezioni e così via. Può essere che abbia sbagliato soprattutto verso la fine perché volevo finire in fretta l'ordinamento degli esercizi e non ho ricontrollato molto.

**Comment by mzanella** [comment]
@herrBez Qui avevi già fatto qualcosa?

**Comment by herrBez** [comment]
Si il commit che vedi nel branch 221-FixExerciseChapter
