### ISSUE TITLE
Spostare esempio pizza

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#225]
**Description**
Alla fine della sezione 12.1.2 si parla dell'esempio di pizzahut. Io lo sposterei dove si parla di Controlli di ragionevolezze. Cancellerei i troppi dettagli sul fatto che negli USA adesso ci sia solo pizzahut.

**Other issues**

**Comment by Polpetta** [comment]
A me piacevano i dettagli 😥  Ma se vuoi spostare l'esempio mettilo pure dove ti pare più opportuno! 😊

**Comment by herrBez** [comment]
Lascio i dettagli ma lo sposto xD. O metto una footnote come piace a te :D

**Comment by herrBez** [comment]
Lascio stare
