### ISSUE TITLE
Eliminare l'attuale Figura 12.1

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#226]
**Description**
La figura sul batch processing non (mi) sembra apportare nessun contributo alla comprensione dell'argomento. Io la elimineri.

Voi?
**Other issues**

**Comment by herrBez** [comment]
La figura ha senso solo se affiancata dal testo come nelle slide. Altrimenti è un po' inutile.

**Comment by Polpetta** [comment]
Boh effettivamente li è buttata un po' così. Per me non cambia niente toglierla o tenerla, senti @mzanella
