### ISSUE TITLE
Sezioni 7.5.6.2/3 come esempi

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#23]
**Description**
Proporrei le sezioni 7.5.6.2 e 7.5.6.3 come degli esempi raggruppandole come sottosezione (se effettivamente sono degli esempi)

**Comment by Polpetta** [comment]
? Non esiste il 7.5.6.3 ma solo il 7.5.6.3 che è chiaramente teoria
![image](https://user-images.githubusercontent.com/5928183/28970903-6fef10ae-792a-11e7-9d0b-c404b25f1ba6.png)

**Comment by mzanella** [comment]
Questo è quello che c'è in `develop` adesso
![image](https://user-images.githubusercontent.com/12596262/28971024-dc03dc16-792a-11e7-88ad-537380643e1a.png)
e mi sembrano degli esempi e 
![image](https://user-images.githubusercontent.com/12596262/28971058-f706aa7a-792a-11e7-8a72-b65a506ff410.png)
questa mi sembra più la parte di teoria

**Comment by Polpetta** [comment]
Hai pullato?

**Comment by Polpetta** [comment]
In ogni caso no, quella è parte di teoria, non sono esempi: non so perché ma il prof ha introdotto prima insieme gli step 6 e 7 e poi si è soffermato a parlare prima di uno e poi dell'altro. Son attività che di solito andrebbero svolte

**Comment by mzanella** [comment]
Ok!
