### ISSUE TITLE
Sottosezioni di 7.7

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#24]
le sottosezioni di 7.7 sono 7.7.0.1, 7.7.0.2 e 7.7.0.3 al posto di 7.7.1, 7.7.2 e 7.7.3. Manca qualche parte o si è andati troppo in profondità con il sezionamento?

**Comment by Polpetta** [comment]
Si, ci siamo incasinati con la divisione in sezione/paragrafi ecc ecc...puoi tirare su di un livello quelle parti li per favore?

**Comment by mzanella** [comment]
Sì. Finisco di leggere tutto e poi sistemo tutto quello che ho segnalato che abbia l'ok e i typo.
