### ISSUE TITLE
Figura 5.2 non è Crittografia a chiave simmetrica

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#244]
**Description**
Secondo me la figura 5.2:
![image](https://user-images.githubusercontent.com/6976484/29748982-5fad9954-8b22-11e7-8c10-2c80fcf713d4.png)
Non si riferisce alla crittografia simmetrica ma molto più probabilmente a quella assimetrica. 
Visto l'utilizzo di due chiavi!
**Other issues**
#243

**Comment by Polpetta** [comment]
Sisi, è quella asimmetrica, sicuro!

**Comment by herrBez** [comment]
Allora huston abbiamo un problema :joy:

**Comment by herrBez** [comment]
Direi di eliminare la figura 5.2(perchè nella sezione sulla crittografia assimetrica c'è già un'immagine). 
Forse potremmo trovare un'immagine per la crittografia simmetrica così da sostituirla.

@Polpetta

**Comment by mzanella** [comment]
- questa è nello stesso stile http://www.linux.it/~davide/doc/tesi_html/img105.png
- http://massimoromano.altervista.org/wp-content/uploads/2016/09/criptazione_simmetrica.png

Se mi dite quale vi piace di più faccio il cambio @herrBez @Polpetta

**Comment by herrBez** [comment]
La prima sembra meno illegale :joy:

**Comment by mzanella** [comment]
ok allora cambio o7

**Comment by Polpetta** [comment]
Voto per la uno anche io! 😁
