### ISSUE TITLE
Sottosezioni di 9

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#25]
**Description**
Le sottosezioni di 9 da 9.0.0.0.1 a 9.0.0.0.6 hanno la numerazione errata. Si tratta di CMM?
(È legata ad una parte della issue #20 punto 5)

**Comment by Polpetta** [comment]
Non so perché la numerazione sia così sinceramente. Li o ci va un `*` per togliere la numerazione o vanno spostati tutte i paragrafi nel livello adatto. Vedi te cosa ti aggrada di più! 😊

**Comment by mzanella** [comment]
Ma fanno parte del CMM o del COBIT? perchè in caso facciano parte del CMM tengo le prime, altrimenti le seconde

**Comment by Polpetta** [comment]
cmm

**Comment by mzanella** [comment]
Ok ma allora i livelli sono 6? (con lo 0)

**Comment by Polpetta** [comment]
Eh me lo son chiesto anche io, però forse lo 0 non conta in quanto è tipo essere dei barboni. Invochiamo @herrBez nella faccenda
