### ISSUE TITLE
Definizione di MTO

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#258]
**Description**
Negli appunti MTO è ancora definito come 
```
Il tempo passato tra l’inizio della modalità alternativa e il ripristino del livello
regolare di servizio viene definito come Maximum Tolerable Outage (MTO).
```
mentre il professore ci aveva detto
```
MTO comprende chiaramente l'IW. 
```

**Comment by herrBez** [comment]
Si, ma la definizione è coerente con l'immagine (dal momento in cui si interrompe fino al servizio regolare è giusto). Se vuoi la cambiamo così:

> MTO: il tempo massimo che può passare tra il momento in cui si interrompe il servizio e il momento in cui viene ripristinato il servizio regolare, include l'interruption window e l'alternate mode. 

Adesso faccio la PR
