### ISSUE TITLE
Stile di pianificazione operazionale in 10.2

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#26]
**Description**
In questa sezione pianificazione strategica e tattica sono segnate in grassetto mentre pianificazione operazionale no. Voluto o si può mettere anche quello in grassetto?

**Comment by Polpetta** [comment]
Penso molto probabilmente sia stata una svista. Senti anche @herrBez, ma
probabilmente va in grassetto anche quella

Il 05 ago 2017 11:09, "mzanella" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si è sicuramente una svista ^^. Chiudo la pull request? E apro una nuova richiesta per la frase del Kaizen dell'usse #35 ?

**Comment by mzanella** [comment]
Va bene!

**Comment by herrBez** [comment]
Chiudo!
