### ISSUE TITLE
Parte della v1x del capitolo 5.3

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#262]
**Description**
Parte delle modifiche per 5.3 per la versione v1x. Così sposto la issue #243 nella milestone v2x
**Other issues**
#243

**Comment by Polpetta** [comment]
Non ho capito

**Comment by herrBez** [comment]
Allora sposto l'issue "grande" nella milestone v2x (da lasciare per i posteri). Mentre ho fatto questa piccola issue per aggiungere le modifiche per la versione 1x.

**Comment by Polpetta** [comment]
Ok.
