### ISSUE TITLE
Aggiungere 'Chain of custody'

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#267]
**Description**
Aggiungere la seguente immagine al documento (con un po' di discrizione)
![screenshot from 2017-09-16 10-18-02](https://user-images.githubusercontent.com/5928183/30510773-a7337e58-9aca-11e7-992f-4636a7843ad2.png)

**Comment by herrBez** [comment]
Dove la piazzo l'immagine?
