### ISSUE TITLE
11.1 Security Operations - 3o punto - frase incompleta

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#27]
**Description**
Nell'ultima frase del 3o punto non si capisce cosa si voleva dire, sembra che manchi un pezzo:

> Una release nuova vuol dire che chi ha il livello di autorizzazione perché una nuova release potrebbe comportare comportamenti anomali;

**Comment by Polpetta** [comment]
Dimmi meglio di che sezione si tratta che senza contesto non mi ricordo il
significato

Il 05 ago 2017 12:08, "mzanella" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Sezione 11.1, Capitolo Security Administrator

**Comment by Polpetta** [comment]
Hahaha cazzo è arabo 😂 Niente dice che i rilasci del software vanno controllati tramite test e documentati, e le release devono essere fatte da chi ha l'autorizzazione necessaria perché se fatte a cazzo di cane potrebbero esserci dei comportamenti anomali nei sistemi

**Comment by mzanella** [comment]
Quindi @Polpetta si potrebbe modificare in:
>Una nuova release deve essere rilasciata solamente da chi posside l'autorizzazione necessaria, poichè potrebbe causare anomalie nel sistema se non sufficientemente testata e documentata;

?

**Comment by Polpetta** [comment]
No, meglio:
> Il rilasci software devono essere prima di tutto testati e documentati, e poi devono essere autorizzati dall'apposito responsabile. Questo procedimento garantisce che il software introdotto nel sistema non causi anomalie

Perché per come me lo ricordo (e l'ho capito) è che diversi team di developer possono fare una release del proprio software, ma questa dev'essere controllata, verificata e approvata da un responsabile prima di andare effettivamente in produzione.

Come l'hai scritta te mi sa tanto da "il responsabile si occupa di fare le release", mentre secondo me questo non va bene perché gli darebbe sia il ruolo di quello che la fa sia di quello che la verifica e la pubblica, quindi mi pare che non ci sia una netta `segregation of duties`, insomma fa tutto lui (quindi potrebbe fare una release infetta e approvarsela, per dire).

Poi eh, è come ho interpretato il tutto 😁 Posso anche aver capito pan per focaccia
