### ISSUE TITLE
Batch processing

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#29]
**Description**
- [x] Seconda frase la cambierei in (unendo con la prima): 

>che prevede l'elaborazione sequenziale di blocchi di transazioni, dopo che queste sono state aggregate

- [x] La 5a frase termina con `:` o frase successiva erroneamente inizia con la maiuscola

>Viene effettuato il processing (es. ordine pagamenti e salvataggio nel DB):

- [x] Le frasi 5 e 6 non sono molto sensate:

>Viene effettuato il processing (es. ordine pagamenti e salvataggio nel DB):Il processing viene completato.

- [x] La figura 13.1 non deve avere scritto niente?

_A mio parere non si capisce molto di questa sezione_ :sweat_smile:

**Comment by Polpetta** [comment]
Di sicuro è successo un casino con la 5/6a frase, vai a vedere se nelle
versioni precedente del file c'era sempre stato o è stato introdotto il
problema con gli ultimi push.
Per la caption della figura se vuoi puoi mettere quello che rappresenta,
non penso ci siano problemi.

Il 05 ago 2017 15:06, "mzanella" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Nella figura non è che manchi la caption ma è tipo un diagramma vuoto

**Comment by mzanella** [comment]
Comunque anche nelle versioni precedenti era così questa parte

**Comment by Polpetta** [comment]
Allora proprio non so

**Comment by mzanella** [comment]
Provate a vedere se vi ricordate qualcosa da lezione? dovrebbe averla scritta @herrBez questa parte

**Comment by herrBez** [comment]
L'immagine è quella delle slide, ma effettivamente vedendola cosí non ha molto senso. Ha più senso la prima frase.

Nel libro (CISA study guide) trovo le seguenti informazioni su batch processing:

**Prima Occorrenza**
> You can
run software slowly in a batch of requests (set of requests, also known as batch mode) or in
smaller and faster batches to simulate real-time transactions.

**Seconda Occorrenza**
> Batch controls  ​ ​Used to ensure the accuracy and correct formatting of input data. The
batch controls include sequence numbering and run-to-run totals. The batch count will 
count the number of all the items to ensure that each transaction is processed. Batch totals
can be used to verify the values within the transactions.

**Terza Occorrenza**
> Most data processing occurs by using a batch processing mode. The data batch may
be small or large. The frequency of processing may be seconds or hours. Regardless of the
method, it is necessary to ensure data integrity by using data validation and edit procedures.
Without operational processing controls, the database would be no more effective than a
garbage can.
Processing controls include the following:
Batch Totals    To compare input against actual processing.
Total Number of Items    To verify that each item was processed.
Transaction Logs    To record activity.
Run-to-Run Totals    To provide verification of the data values during the different stages of
processing. This helps ensure the completeness of all transactions.
Limit Checks    To prevent processing of any amount in excess of the expected aver-
age. Overly large transactions will not be processed. For example, no employee should
receive a paycheck for $50,000. That amount would obviously be excessive outside of
executive positions.
Exception Reporting    To identify errors. The exception may hold the batch in suspension
until the errors are corrected, or reject individual transactions containing errors, or reject
the entire batch of transactions.
Job Cost Accounting    The operating cost of computer processing may be billed to a par-
ticular department, project, or application. It is important to observe the effectiveness of
job cost accounting when it is used.

**Comment by herrBez** [comment]
@mzanella potresti fare una pull-request con questo contenuto cosí è piú facile vedere che modifiche vorresti apportare?

**Comment by herrBez** [comment]
ping @mzanella

**Comment by herrBez** [comment]
pong @mzanella

**Comment by herrBez** [comment]
ping @mzanella

**Comment by Polpetta** [comment]
😅

**Comment by herrBez** [comment]
pong @mzanella

**Comment by herrBez** [comment]
Ormai è tradizione

ping @mzanella

**Comment by mzanella** [comment]
Io provo a fare le modifiche il problema è che di questa parte non ci ho capito una cippa

**Comment by herrBez** [comment]
Da come ho capito io non c'è niente di difficile: 
Invece di analizzare una transazione alla volta le raccogli in "batch" e li controlli così. Comunque le slide aiutano ^^
