### ISSUE TITLE
13.1.0.0.5 Error Handling Alternatives - termine "fissate"

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#30]
**Description**
il 3o punto dice:

>Tieni il batch in sospeso fintanto che le transazioni non vengono fissate;

Doveva essere `fixate` o è corretto?

**Comment by mzanella** [comment]
@Polpetta cambio o lascio?

**Comment by Polpetta** [comment]
Si è `fixate`. Comunque è anche `tenere` non `tieni`
