### ISSUE TITLE
Aggiungi vocabularly Slide 5/41 delle frodi

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#32]
**Description**
aggiungere la slide 6/41 sulle frodi (vocabolario). 
Va bene se lo aggiungo? @mzanella @Polpetta 
**Other issues**
Aggiungere la nota sul fatto che la somma delle percentuali di come si scopre una frode non dia 100% come indicato in questo link https://www.google.it/search?q=how+fraud+is+discovered&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjrkbjR58TVAhVDSBQKHcXTBRUQ_AUIDCgD&biw=1680&bih=920#imgrc=LqoiTSI-Wxt0wM:

**Comment by Polpetta** [comment]
Per me è ok

**Comment by mzanella** [comment]
Vai

**Comment by herrBez** [comment]
Chiudo l'issue perché la pull-request è stata chiusa

**Comment by Polpetta** [comment]
Ok! ho modificato il template così si dovrebbero chiudere da sole in futuro
quando la PR viene accettata

Il 08 ago 2017 19:37, "herrBez" <notifications@github.com> ha scritto:
