### ISSUE TITLE
Audit per le frodi

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#39]
**Description**
Nell'elenco della sezione 1.1.4 viene detto che la scoperta delle frodi avviene anche grazie a audit interni e esterni, mentre nella sezione 1.2.1 c'è scritto che non è possibile fare detection di frodi tramite audit. Ci si riferisce a due cose differenti o sono due parti in contrasto?

**Comment by Polpetta** [comment]
L'audit sui processi non può scoprire l'avvenimento di frodi.

Non son due parti in contrasto secondo me. Poi questo è quello che ha detto
il prof in classe, io ho solo trascritto.
Può essere che nella prima lista descrivesse l'audit come uno strumento per
migliorare i processi (tipo inserendo controlli nei processi, suddivisione
dei ruoli o generazione di documentazione adeguata) e che il miglioramento
dei processi porti come conseguenza una maggiore difficoltà per un
dipendente a portare a termine una frode.

Io l'ho interpretata nella seguente maniera.

Il 08 ago 2017 17:20, "mzanella" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si potrebbe chiedere anche questo al professore cosí abbiamo due domande da fare a Di Pietro ^^ (Issue #41). Cosa ne pensate?

**Comment by Polpetta** [comment]
Va bene!

Il 08 ago 2017 22:37, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Anche per me

**Comment by mzanella** [comment]
Comunque guardando le slide mi sembra leggermente differente... Infatti c'è scritto:
>Audits are not designed to detect fraud

Che mi pare differente da:
>L’audit verifica che le cose vadano com’è stato dichiarato, quindi non è possibile eseguire detection di frodi tramite questo tipo di controllo.

**Comment by herrBez** [comment]
Concordo con @mzanella. Comunque aspettiamo la risposta di Di Pietro :)

**Comment by mzanella** [comment]
è comunque possibile trovare le frodi tramite gli audit? 

Certamente. Accade in particolare durante le interviste, in cui puo' apparire evidente qualche misalignement che potrebbe essere indizio di frode.
