### ISSUE TITLE
Habits di un fraudolento/povere abitudini lavorative

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#40]
**Description**
Non capisco cosa si intenda per povere abitudini lavorative. Qualcuno me lo può spiegare? :sweat_smile:

**Comment by Polpetta** [comment]
Si intende con il fatto di lavorare in modo strano (orari di lavoro molto
estremi, molto tardi o presto), non condividere alcuni documenti di lavoro,
cercare di raggiungere in maniera disperata gli obiettivi lavorativi e/o
non andare in vacanza!

Questo si intende per povere abitudine lavorative, ovvero tutto
quell'insieme di azioni fuori dalla norma

Il 08 ago 2017 17:20, "mzanella" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Quindi praticamente quello che è spiegato sotto, vero?

**Comment by herrBez** [comment]
Sostanzialmente si. Se vuoi possiamo provare a riformulare...

**Comment by Polpetta** [comment]
Si, è quanto scritto sotto. Secondo me va bene così, ma se è poco chiaro
apri una PR con la tua idea su come riscrivere quella parte li che ne
discutiamo la.

Il 08 ago 2017 19:36, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Non credo era solo per capire! Cosa dici @herrBez?

**Comment by herrBez** [comment]
Close and Comment
