### ISSUE TITLE
Definizione di Maximum Tolerable Outage

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#41]
**Description**
Nella sezione 2.2.2 il Maximum Tolerable Outage è definito come 
>Il tempo passato tra l’inizio della modalità alternativa e la sua conclusione con il ripristino delle normali operazioni

ma nella figura 2.1 il MTO comprende anche l'Interruption Window. Mi sono perso qualcosa?

**Comment by herrBez** [comment]
Ciao, sulle slide c'è scritto "Max time in Alternate Mode", ma in teoria dovrebbe essere la la [seguente](http://www.opscentre.com/is-that-maximum-tolerable-outage-maximum-tolerable-disruption-or-what/)? :

> Maximum tolerable outage or MTO is a common measure in both disaster recovery and business continuity. It is the maximum amount of time a system or resource can remain unavailable before its loss starts to have an unacceptable impact on the goals or the survival of an organisation.

Cioé dovrebbe essere proprio il tempo massimo dopo il quale diventa troppo oneroso andare in alternate mode/senza servizio. 

Questo spiegherebbe anche il significato di maximum ^^ Altrimenti massimo da solo non significa niente

**Comment by Polpetta** [comment]
Hai provato a confrontare con le slide del prof? Perché se vedi
nell'immagine che c'è negli appunti (vado a memoria) il MTO è una grafia
tra quanto succede il disastro a quando il servizio torna a funzionare
normalmente

Il 08 ago 2017 19:33, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Esatto @Polpetta

**Comment by Polpetta** [comment]
Mi sa che la frase è formulata male allora :/ di sicuro lo schema non è
sbagliato in quanto abbiamo preso dalle slide del prof

Il 08 ago 2017 19:02, "mzanella" <notifications@github.com> ha scritto:

**Comment by Polpetta** [comment]
Che dicono le slide del prof riguardo l'MTO?

Il 08 ago 2017 20:27, "mzanella" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Le slide dicono solo Max time in Alternate Mode

**Comment by Polpetta** [comment]
Quello che abbiamo scritto nelle slide no?

Il 08 ago 2017 21:45, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si ma è in evidente contrasto con l'immagine e la definizione di internet

**Comment by Polpetta** [comment]
E se chiedessimo per e-mail al prof?

Il 08 ago 2017 22:18, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si potrebbe fare, ma direi di scrivere una lista di (almeno 2?) domande, cosí da inviare una sola email prima di ferragosto

**Comment by Polpetta** [comment]
Okok

Il 08 ago 2017 22:35, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
MTO comprende chiaramente l'IW.
