### ISSUE TITLE
Integrare le considerazioni etiche della frode con quelle della slide 7/41

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#42]
**Description**
Integrare le considerazioni etiche della frode con quelle della slide 7/41? Cosa ne pensate
**Other issues**
Potrebbe anche dare una mano a risolvere l'issue #17

**Comment by Polpetta** [comment]
Bah, secondo me non è una cosa tanto rilevante ai fini del corso, però se vuoi sei libero di aggiungerla!

**Comment by herrBez** [comment]
Non so la aggiungerei solo perchè c'é l'esercizio 7...

**Comment by Polpetta** [comment]
Va bene 😊

**Comment by mzanella** [comment]
Non ho capito mica cosa vorresti mettere in più :sweat_smile: 

Vorresti aggiungere tutto quello che c'è scritto in questa slide alla sezione 1.1.2 @herrBez ?
![image](https://user-images.githubusercontent.com/12596262/29123914-988710de-7d17-11e7-89b6-eea71a9a521b.png)

**Comment by herrBez** [comment]
Si una roba del genere. Ma forse teniamo così alla fine sappiamo anche noi che per essere frodi devi volerlo fare (cioè deve esserci il dolo)

**Comment by Polpetta** [comment]
Appunto secondo me basta questo. Chiudi te @herrBez la issue se ti senti convinto

**Comment by herrBez** [comment]
Ok chiudo!
