### ISSUE TITLE
Riformulare/Sistemare la frase riguardante il Kaizen

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#43]
**Description**
Ciao, secondo me è da sistemare a frase del Kaizen (scusate il gioco di parole :D ):

    Quando vedete una freccia circolare bisogna pensare al PDCA (Plan Do Check
    Act). Infatti, ormai tutti i progetti sono circolari. Kaizen è una parola giapponese
    che vuol dire “miglioramento continuo” Scostamento tra valore atteso e valore
    ottenuto. Quando si vede che c’è un delta si cerca di operare per migliorarlo. Una
    volta raggiunto l’obiettivo, bisogna migliorare.

Non capisco La frase dove c'è Kaizen. Cioè lo Scostamento continuo a cosa si riferisce?
**Other issues**

**Comment by Polpetta** [comment]
Sbaglio o c'era già una issue simile aperta? @mzanella

Il 08 ago 2017 21:30, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
La abbiamo chiusa perchè riguardava qualcos'altro ed era un off-topic. Questa è una issue specifica per questa frase. (Quella di prima si riferiva solo agli 80 caratteri del file)

**Comment by Polpetta** [comment]
Okok

Il 08 ago 2017 22:19, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Come avevo scritto sull'altra PR io la cambierei così:
>Quando vedete una freccia circolare bisogna pensare al PDCA (Plan Do Check Act). Infatti, ormai tutti i progetti sono circolari. Kaizen è una parola giapponese che vuol dire “miglioramento continuo”. Quando si vede che c’è un delta, ovvero uno scostamento tra valore atteso e valore ottenuto, si cerca di operare per migliorarlo. Una volta raggiunto l’obiettivo, bisogna migliorare.

Ma non so se era questo a cui ci si riferiva però :sweat_smile:

**Comment by Polpetta** [comment]
Eh dipende. In caso fai già una PR con la modifica e assegna @herrBez che velocizziamo la cosa 😅

**Comment by herrBez** [comment]
Si anche secondo me va bene, anche se non capisco la differenza tra PDCA e Kaizen.
Dopo una breve ricerca mi è parso di capire che il PDCA sia un modo di implementare il Kaizen (Kai = miglioramento, zen = buono)

**Comment by herrBez** [comment]
Anche se ora non capisco "Una volta raggiunto l’obiettivo, bisogna migliorare.". Questo è vero sempre o solo quando c'è uno scostamento?

**Comment by Polpetta** [comment]
Penso che non sia mai possibile raggiungere la perfezione, da qui il miglioramento continuo forse?

**Comment by herrBez** [comment]
Ok. Allora teniamo la frase e chiudiamo. va bene?

**Comment by Polpetta** [comment]
As you wish

**Comment by herrBez** [comment]
Non sei convinto?

**Comment by Polpetta** [comment]
Nono nel senso che io non ci avevo visto nessun problema in quella frase quindi dovete decidere voi se cambiarla o meno! Per me è ok così com'è 😁

**Comment by mzanella** [comment]
Ma tipo il PDCA non dice che bisogna fissare degli obiettivi e quando si sono raggiunto fissare quelli "del giro dopo"? Non è magari che si intenda quello con `Una volta raggiunto l’obiettivo, bisogna migliorare.`?
