### ISSUE TITLE
Habits di un fraudolento --> Abitudini di un fraudolento

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#44]
**Description**
Abbiamo tradotto tutto, a sto punto tradurrei anche il titolo di capitolo 1.2.3.
Inoltre nello stesso paragrafo c'è una traduzione sbagliata o imprecisa. Sulle slide c'è scritto:

> Voided checks or receipts, with no explanation

Sugli appunti è stato tradotto con:

> Le consegne ricevute non vengono consegnate; 

A me non sembrano corrispondere 1:1. Cosa dite?

**Other issues**

**Comment by Polpetta** [comment]
Va bene! 😊

**Comment by herrBez** [comment]
Ok. Ma ho editato la domanda. Guarda anche la seconda parte? (Sono un mona avrei dovuto commentare)

**Comment by Polpetta** [comment]
Riguardo alla storia delle consegne, questo era quello che probabilmente aveva detto lui in classe, si potrebbe dire che `le consegne vengono modificate o annullate senza alcuna ragione`
