### ISSUE TITLE
Manca tutta la slide su Business Application Checks 28/41

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#46]
Manca tutta la slide e in teoria dovrebbe anche spiegare cosa c'entra la PO Box

**Comment by Polpetta** [comment]
Se vuoi puoi aggiungerla prima della PO Box, anche se vedendo solo la slide così sinceramente non saprei molto cosa dire a riguardo

**Comment by herrBez** [comment]
Effettivamente non so neanche io, sto cercando nel libro che ha messo sotto come riferimento. Ma non trovo granchè...

**Comment by Polpetta** [comment]
Quindi che si fa?

**Comment by mzanella** [comment]
Si potrebbe aggiungere:
>Business Application Checks  Gli assegni dovrebbero essere tenuti in un luogo con accesso ristretto e se ne dovrebbe fare l'inventario almeno ogni trimestre. Le informazioni di nuovi venditori dovrebbero essere ricontrollato dell'amministrazione (o direzione??). In caso ci siano assegni restituiti, questi devono essere mandati ad fermo posta e valutati da qualcuno esterno all'azienda.

L'ultima frase non so come metterla giù. @herrBez @Polpetta che dite?

**Comment by Polpetta** [comment]
Io userei `transazioni` al posto di `assegni`, perché per tutto il resto del documento abbiamo fatto così e qualcuno rischia di confondersi se ad un certo punto tiri fuori gli assegni così dal nulla

**Comment by mzanella** [comment]
Ma ha senso dire che le transazioni devono essere tenuti in un luogo con accesso limitato?

**Comment by Polpetta** [comment]
Non so perché sinceramente ora sta parola mi mette confusione.
Se leggi il capitolo 13-14 usa il termine transazione anche in altri contesti fuori dalla semantica di scambio monetario, quindi non saprei se transazione sta tipo per `cosa generica` o è un qualcosa specifico che però non ha mai specificato in tutto il corso

**Comment by mzanella** [comment]
Oddio non so... Però di certo in questo caso non ci sta per me:sweat_smile: @herrBez dicci la tua

**Comment by herrBez** [comment]
Beh in questo caso anche a me suona meglio assegno soprattutto perchè non posso mettere una transazione in una P.O. Box. Inoltre anche nel libro da cui lo ha preso sembra che parli di assegni:

> Or forgers drive to a wealthy neighborhood and park in a grocery
store parking lot. They wait until you pull in in your Porsche or
your Jaguar and they follow you into the store. You buy groceries.
You have to write your check on a little pad that's sticking up on the counter. 
They're right next to you, loading items onto the
counter. They look over your shoulder—most of them are
women—and they can memorize your check in eight seconds. All
they have to do is glance over your shoulder. You haven't gotten
past writing the date, and they've memorized it. Everything on it.
They go back and fill out an order coupon. Name and address
you'd like on the check? They put your name and address on the
check. Style of check? You've got flags on your check, so they
order checks with flags. How many? Two hundred. Last question:
if you'd like these checks sent to an address other than the printed
address on the face of the check, so state here. They fill in a P.O.
Box. Ten days later, they've got your checks.

Anche se questo testo non mi è chiaro al 100% :sweat_smile: 

D'altro canto non mi sembra che Di Pietro avesse parlato di assegni. Ma forse non ricordo. Purtroppo non abbiamo pensato a prendere le registrazioni :disappointed:

**Comment by Polpetta** [comment]
Appunto. Quindi dobbiamo un po' improvvisare qui, o chiedere a lui

**Comment by herrBez** [comment]
Io chiederei se può descrivere in due parole il contenuto della slide. Anche se non saprei come formulare la domanda da fargli :sweat:
