### ISSUE TITLE
Integrerei un po' con le slide la sezione su "Software Per trovare frodi"

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#47]
**Description**
Integrerei con le slide la sezione su Software per trovare frodi, in particolare (Slide 25/41) direi in cosa possa contribuire. Almeno 2/5 esempi, giusto per capire concretamente che  cosa possono controllare.

**Other issues**

**Comment by Polpetta** [comment]
Va bene, anche se dubito ti chiederà di parlare di questa cosa qui all'esame. Però un paio di esempi non fanno male, di sicuro aiutano a capire!

**Comment by herrBez** [comment]
Ciao guarda i due commit. Se vuoi il secondo può essere ignorato. Ho preso la frase del secondo commit dal libro (Se secondo voi è inutile la tolgo)

**Comment by Polpetta** [comment]
In che branch sono?

**Comment by herrBez** [comment]
Nel branch Issue47 (nome di fantasia ^^)

**Comment by herrBez** [comment]
@Polpetta @mzanella  Riuscite a darci un 'occhiata così la chiudiamo? Anzi apro la pull-request
