### ISSUE TITLE
Immagine senza didascalia

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#48]
**Description**
Nel capitolo 2.5.5.1 c'è un'immagine senza didascalia. E cosí su due piedi non si capisce (E neanche la sigla IPF)
**Other issues**

**Comment by mzanella** [comment]
Ti riferisci alla tabella @herrBez?

**Comment by herrBez** [comment]
Si a quella tabella che però è un'immagine

**Comment by mzanella** [comment]
IPF è corretto definirlo come 
>Information Processing Facility: impianto di elaborazione delle informazioni ovvero un qualsiasi sistema, servizio, infrastruttura o qualsiasi posizione fisica che ospita queste cose. Un IPF può essere un'attività o un luogo e può essere tangibile o immateriale.

Come descrizione dell'immagine non so bene cosa mettere:sweat_smile:

**Comment by herrBez** [comment]
La definizione di IPF è oro (nel mio libro lo definisce come:
> Information processing facility (IPF)  ​ ​T he building that houses the data center.

Ma la tua è più completa. 

Per quanto riguarda l'immagine non saprei neanche io chiediamo all'Owner ^^ @Polpetta

**Comment by Polpetta** [comment]
Puoi usare la versione figa di caption:
```tex
\caption[Information processing facility (IPF) ​ ​The building that houses the data center]
{Information Processing Facility: impianto di elaborazione delle informazioni ovvero un 
qualsiasi sistema, servizio, infrastruttura o qualsiasi posizione fisica che ospita queste 
cose. Un IPF può essere un'attività o un luogo e può essere tangibile o immateriale.}
```

Così sotto l'immagine hai una bella didascalia che spiega il tutto mentre nell'index principale non hai tutto una sbrodolata di testo che descrive l'immagine ma il suo titoletto nelle parentesi quadre!

Che ne dite come idea? 😊  (ovviamente il titoletto dev'essere tradotto in italiano così è ancora più figo)

**Comment by mzanella** [comment]
Eh ma non descrive l'immagine:sweat_smile:

**Comment by Polpetta** [comment]
😁 Per me quella tabella è un esempio comunque

**Comment by mzanella** [comment]
Va bene quindi cosa mettiamo lo stesso come caption?:joy:

**Comment by Polpetta** [comment]
Boh 😁
