### ISSUE TITLE
Sezione 2.5.5 e paragrafo 2.5.5.2 sembrano uguali

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#51]
**Other issues** #20

**Comment by herrBez** [comment]
concordo! Infatti non ci sono due slide distinte nel pacco di slide su quel tema lì. È evidentemente un duplicato!

**Comment by Polpetta** [comment]
L'ho fatto così perché siccome volevo mettere il contenuto sotto la tabella non sapevo come fare per dire che si trattava dell'argomento precedente quindi ho ripetuto il titolo

**Comment by mzanella** [comment]
Ma anche i contenuti sono praticamente uguali. Si possono unire?

**Comment by Polpetta** [comment]
Si unisci

**Comment by mzanella** [comment]
Ok perfetto
