### ISSUE TITLE
Figura 6.2 e 6.4 sono uguali

### ISSUE THREAD

**Issue by mzanella** [Polpetta/SecurityAndRiskManagementNotes#53]
**Description**
Non so se deve essere tolta una o devono comparire entrambe
**Other issues** #20

**Comment by mzanella** [comment]
@Polpetta dimmi e eseguo

**Comment by Polpetta** [comment]
Ma se non sbaglio erano state messe appositamente da @tfederico, dal cui probabilmente non otterrai mai una riposta :grin:
