### ISSUE TITLE
Duplicazione 3.3

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#58]
**Description**
Nella sezione 3.3 proprio nell'introduzione c'è un elenco puntato e numerato che viene ripetuto nella parte più discorsiva, dando vita ad elementi ridondanti
**Other issues**
#20

**Comment by Polpetta** [comment]
La label `duplicate` sta ad indicare una issue ripetuta. Forse dovremmo farne una e chiamarla `duplication` per indicare duplicazioni nel testo

**Comment by Polpetta** [comment]
Comunque si hai ragione, questo è stato fatto perché mentre prendevamo appunti uno copiava la slide e un altro scriveva quello che stava dicendo il prof.
Ci sono due possibiltà:
- Scrivi il discorso nell'elenco puntato
- Cancelli l'elenco puntato e tieni il discorso, assicurandoti che comunque tutte le parole chiave dell'elenco puntato siano presenti nel discorso stesso
