### ISSUE TITLE
Sezione 3.4 Scrivere le responsabilità di tutti i ruoli

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#59]
**Description**
Finirei di copiare dall'immagine delle slide (6/43 di Information Security) le responsabilità dei ruoli elencati
**Other issues**

**Comment by herrBez** [comment]
Non mi è chiaro perchè il data owner nei nostri appunti: 

> si occupa di decidere chi è 
  responsabile all'accesso al dato. 

In teoria secondo la slide 6 è il responsabile della sicurezza del dato quindi non decide chi è responsabile ma è lui responsabile.
Inoltre aggiungerei un po' di info accessorie dalla slide 7

**Comment by herrBez** [comment]
Ho pushato nel branch fix59 le modifiche che ho intenzione di fare manca solo quanto scritto nel commento precedente

**Comment by Polpetta** [comment]
> In teoria secondo la slide 6 è il responsabile della sicurezza del dato quindi non decide chi è responsabile ma è lui responsabile.

Allora è chiaramente un errore di traduzione e va sistemato! Bella lì 👍

**Comment by herrBez** [comment]
Ho rebasato il branch `59-Fix` per renderlo papabile per una pull request ma non sono sicuro di avere fissato anche l'ultimo punto evidenziato nei commenti precedenti
