### ISSUE TITLE
Do the todo?

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#6]
Nel File : 16-Les21032017.tex c'è il todo che dice di aggiungere la tabella nella sezione role-based access control. Guardandola non mi sembra molto importante. La aggiungiamo o no?

**Comment by Polpetta** [comment]
Sentiamo anche @tfederico che dice. Se non serve non mettiamo roba, che allunga solo il brodo inutilmente 😁

**Comment by tfederico** [comment]
A me sembrava utile perché indicata anche i tipi di permessi (rwx) oltre che ai ruoli, altrimenti quella section dice tutto e niente

**Comment by Polpetta** [comment]
Va bene allora, mettiamola!! :blush:

Il 15 apr 2017 19:07, "Federico" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
ok, quando la inserisco chiudo l'ISSUE (probabilmente dopo il compitino di Data Mining)

**Comment by Polpetta** [comment]
Sisi tanto non c'è fretta :+1:

Il 15 apr 2017 19:30, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Grande @Polpetta :) Chiudo l'issue
