### ISSUE TITLE
Sezione 3.5 Classificazione della sicurezza

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#61]
**Description**
Non dovrebbe essere come nelle slide classificazione della criticità? Inoltre aggiungerei un riferimento alla sezione 2.3 che ha lo stesso elenco puntato e spiega le singole voci
**Other issues**

**Comment by mzanella** [comment]
Non capisco la differenza con le slide @herrBez 
Per il riferimento sono d'acccordo

**Comment by herrBez** [comment]
Dico che non è la classificazione della sicurezza, quanto piuttosto quella di criticità come nel capitolo 2.3 e  nel titolo della slide

**Comment by mzanella** [comment]
Aaaaa allora sì sono d'accordo
