### ISSUE TITLE
La sezione 4 non dovrebbe esistere?

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#62]
**Description**
Ciao scusate sto guardando gli appunti ma non capisco perchè esista l'attuale sezione 4. Secondo me dovrebbe fare parte della sezione 3 cosí rispetterebbe l'ordine delle slide e anche l'introduzione del capitolo 3..
**Other issues**

**Comment by Polpetta** [comment]
Dici sezione o parte? Non capisco 😅

**Comment by herrBez** [comment]
Dico il capitolo 4 dovrebbe stare sotto il capitolo 3 oppure dovremmo cambiare l'introduzione del capitolo 3.
Infatti quest'ultima dice che:

> Obiettivi: principi della sicurezza dell’informazione, posizioni all’interno degli
organigrammi della gestione della sicurezza, tecniche di accesso controllato, tecniche
di autenticazione, tecniche di combinazione, tecniche biometriche, elementi del
Bell-LaPadula, elementi di sicurezza militare, backup e schemi di classificazione
dell’informazione.

Ma tutta la parte sulle tecniche di accesso controllato, tecniche di autenticazione ecc. sono nel capitolo 4.

**Comment by Polpetta** [comment]
È che l'information security non dovrebbe essere un capitolo, dovrebbe essere una sezione che raggruppa quel capitolo e quello successivo

**Comment by herrBez** [comment]
Si hai ragione.  Quindi come dici di sistemare?

**Comment by Polpetta** [comment]
O mettiamo quella come `part` e tiriamo su tutte le section, subsection ecc di un livello oppure non saprei, non vedo altra soluzione 😅

**Comment by herrBez** [comment]
Questa è una proposta, anche se sinceramente non sono convinto neanche io perché il tutto diventa 4 pagine più lungo da 208 a 212. Ma diventa più sensata l'introduzione. 
Cosa ne pensate @mzanella  @Polpetta? 
Faccio una pull-request cosí ci pensate. Potete anche rifiutarla, ma almeno chiudiamo l'issue :)
