### ISSUE TITLE
Controlli compensativi in lista dei controlli anti-frode

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#63]
**Description**
Nella sezione delle frodi c'è la lista dei tipi di controlli per contrastarle (preventivi, rivelativi, correttivi), poi nella sezione dopo di parla di controlli compensativi. Secondo me i controlli compensativi andrebbero spostati insieme agli altri tipi di controlli
![screenshot_20170801_170934](https://user-images.githubusercontent.com/5928183/29126356-6e99d0ac-7d1e-11e7-87f5-6c83c41fcf4c.png)

**Other issues**

**Comment by herrBez** [comment]
Credo che ora come ora sia cosí perchè nella slide 21/41 si parla dei 3 tipi di controllo e più avanti slide 24/41 si parla dei controlli compensativi. Forse potremmo spostarlo nella lista precedente specificando che vanno fatti i controlli compensativi quando non è possibile la segregation of duties come nella slide 24.

Anzi scherzavo sposta pure! @mzanella  che ne pensi?

**Comment by mzanella** [comment]
Anche per me si può spostare

**Comment by Polpetta** [comment]
:+1:
