### ISSUE TITLE
80 caratteri

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/SecurityAndRiskManagementNotes#64]
**Description**
Nel file  res/sections/15-Les15032017.tex è stato mergiata una PR contenente righe con più di 80 caratteri, è da mettere a posto

**Other issues**
#57

**Comment by herrBez** [comment]
Per favore non toccate il file 15-... per un po' sto sistemando la sezione 3.3, non vorrei ci fossero dei conflitti dopo

**Comment by Polpetta** [comment]
Sisi l'ho assegnata a te!
