### ISSUE TITLE
Esercizio 8  - Risposta sospetta

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#7]
L'ammontare di dati che si puó perdere da un malfunzionamento del computer si definisce come:

- Recovery Point objective 

-  o Maximum tolearble autage

Durante lezione Di Pietro disse Recovery Point objective, oggi durante il ripassone Maximum tolearable outage

**Comment by Polpetta** [comment]
![image](https://user-images.githubusercontent.com/5928183/26869027-3b3fa838-4b6b-11e7-89c1-9a88212a845b.png)

Giusto per referenza

**Comment by Polpetta** [comment]
Questa la possiamo chiudere o vogliamo scrivere al prof per sicurezza?

Il 07 giu 2017 10:19 AM, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Si anche secondo me è la 2. La chiudo
