### ISSUE TITLE
Access Control Techniques

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#70]
**Description**
non mi sembra corretta la traduzione per `Discretionary Access Control` infatti la slide dice:

> Person with permissions controls access

che in italiano dovrebbe essere

> La persona con i permessi controlla l'accesso (ovvero chi avrà accesso alla risorsa)

Il che corrisponderebbe anche alla definizione del libro del CISA (Prima frase):
>   Discretionary access controls (DACs) allow a designated
individual to decide the level of user access. DAC access is usually distributed across the
organization to provide flexibility for specific use or adjustment to business needs. The data
owner determines access control at their discretion. The IS auditor needs to investigate
how the decisions concerning DAC access controls are authorized, managed, and regularly
reviewed. Most businesses use discretionary access control.

Mentre negli appunti è scritto
> Persone che hanno l'autorizzazione ad accedere. 

Che mi sembra una traduzione molto discostante da quella inglese
**Other issues**

**Comment by herrBez** [comment]
Inoltre penso che 

> Physical Access Control: è quell’area legata alla sicurezza fisica, ed è
legata al CSO ultimamente. Si costituisce di lucchetti, chiavi, ecc. 

Si riferisca invece che al CSO al CISO come già accennato nella sezione 3.4.

Integro anche questo o procedo alla pull-request

**Comment by Polpetta** [comment]
Per la prima parte hai ragione, mentre non ho capito la parte sul CSO.

Il 09 ago 2017 22:27, "herrBez" <notifications@github.com> ha scritto:

**Comment by herrBez** [comment]
Allora nel capitolo 3.4 diciamo che esiste il CSO (Chief Security Officer) che si occupa di sicurezza fisica e il CISO (Chief Information Security Officer). E sempre in quel capitolo diciamo anche che ultimamente il CISO fa anche da CSO. 

> CISO: in principio non esisteva, adesso sta prendendo il sopravvento. Ricopre
anche il ruolo del CSO;

(In ogni caso questa frase l'ho già migliorata nel branch Fix59). 


Quindi visto che c'è l'avverbio ultimamente direi CISO invece che CSO, perchè se no l'ultimamente non ha molto senso!
Se mi date l'ACK correggo e apro la pull-request

**Comment by Polpetta** [comment]
> Quindi visto che c'è l'avverbio ultimamente direi CISO invece che CSO, perchè se no l'ultimamente non ha molto senso!

Diresti CISO al posto di CSO per cosa? :blush:

**Comment by herrBez** [comment]
In questa frase:
> Physical Access Control: è quell’area legata alla sicurezza fisica, ed è
legata al CSO ultimamente. Si costituisce di lucchetti, chiavi, ecc.

Userei CISO invece che CSO, in virtú dell'avverbio `ultimamente`. Per tutto il discorso che ho fatto nei commenti precedenti ..

**Comment by Polpetta** [comment]
Ok, però io farei una `footnote` alla fine della frase dicendo che comunque, come già detto in precedenza, questo era di competenza del CSO. Così lo ricordiamo al lettore. Che te ne pare?

**Comment by herrBez** [comment]
Non sono un grande amante delle footnote (quando si possono evitare) perchè rendono la lettura più difficile, peró in questo modo non so come buttare giù la frase ^^ quindi non zo:

> Physical Access Control: è quell’area relativa alla sicurezza fisica, che si occupa di lucchetti, chiavi ecc.
Questa competenza è tradizionalmente legata al ruolo del CSO, anche se ultimamente si sta affermando come parte del ruolo del CISO.

Mi suona un po' male anche questa versione. Se riesci a buttarmi una bozza di una versione con la footnote ci ragiono un po' ^^

**Comment by Polpetta** [comment]
```tex
Physical Access Control: è quell’area legata alla sicurezza fisica, ed è
legata al CISO ultimamente\footnote{Ricordiamo al lettore come
precedentemente questa responsabiltà era coperta dal CSO, che sta
pian piano venendo soppiantato dal CISO}. Si costituisce di lucchetti,
chiavi, ecc.
```

Poi boh, io sono un po' un fan dei `footnote` perché se non ho voglia di leggere degli approfondimenti non distolgo lo sguardo dalla lettura e non devo saltare da nessuna parte 😅

**Comment by herrBez** [comment]
Ah, io invece non ce la faccio, devo leggere la footnote. Comunque prendiamo la tua versione :) o chiediamo a @mzanella

**Comment by mzanella** [comment]
Va bene la versione di @Polpetta per me
