### ISSUE TITLE
Aggiungere Immagine e definizione su Equal Error Rate Sezione 4.6.6 Slide 31/44

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#72]
**Description**
Nella slide sulla biometria si vede un'immagine che tiene anche presente l'equal error rate. Secondo me ha senso inserire sia l'immagine che la definizione (Anche se prenderei l'immagine 
![image](https://user-images.githubusercontent.com/6976484/29160070-2dc60cc4-7db1-11e7-8623-e1bae4ed42a0.png) dal libro CISA 
study guide )
Anche in virtù del fatto che nella sezione 4.6.6.1 viene usato ERR. 

Comunque possiamo inserire anche solo la definizione (anche se secondo me l'immagine rende di più l'idea che al crescere di uno diminuisce l'altro).
**Other issues**

**Comment by Polpetta** [comment]
Ok! :+1:

Il 10 ago 2017 09:50, "herrBez" <notifications@github.com> ha scritto:
