### ISSUE TITLE
Sezione 4.8.1 elenco puntato

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#73]
**Description**
L'elenco puntato della sezione 4.8.1 che corrisponde alla slide 40/43 di Information Security, consta di soli due punti, mentre nelle slide c'è un elenco di 5.

> + Mantenere i backup dei dati lontani dall’azienda (off-site);
> + Avere un posto sicuro in cui tenere le librerie/siti. Se questi siti hanno
informazioni sensibili è meglio tenerlo in un posto nascosto, la cui conoscenza
è ristretta a pochi.

Mentre nelle slide abbiamo 5 punti:
> Backups are kept off-site (1 or more)
 Off-site is sufficiently far away (disaster-redundant)
 Library is equally secure as main site; unlabelled
 Library has constant environmental control
(humidity-, temperature-controlled, UPS,
smoke/water detectors, fire extinguishers)
 Detailed inventory of storage media & files is
maintained

Forse possiamo anche tralasciarli. Volevo solo evidenziare il problema per prendere una decisione insieme a voi! 

**Other issues**

**Comment by mzanella** [comment]
Possiamo aggiungere:
>- L'ambiente delle librerie deve essere controllato costantemente(umidità, temperatura, UPS, sistemi anti-incendio);
>- Deve avere un inventario aggiornato dei supporti di memorizzazione e dei file salvati

**Comment by mzanella** [comment]
Allora aggiungo io

**Comment by herrBez** [comment]
Grazie :+1:
