### ISSUE TITLE
Manca nel capitolo 4.8.2.1 uno strumento per l'audit trail

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#74]
**Description**
![image](https://user-images.githubusercontent.com/6976484/29161162-75e788a8-7db5-11e7-9fbb-35c7e55f0526.png)

Nel capitolo 4.8.2.1 un punto della slide (scritto in grassetto) non viene proprio menzionato! 

> Attack/Signature Detection: A sequence of log events may
signal an attack (e.g., 1000 login attempts)

**Other issues**

**Comment by Polpetta** [comment]
È da aggiungere allora!

Il 10 ago 2017 10:21, "herrBez" <notifications@github.com> ha scritto:

**Comment by mzanella** [comment]
Si può aggiungere solamente:
>È utile, infine, fare la \textbf{Attack/Signature detection}, ovverio avere una sequenza di log dei tentativi di accesso, in modo tale da verificare se ci sono stati dei tentativi di attacco.

?

**Comment by herrBez** [comment]
Ottimo. Inserisco e apro la pull-request

**Comment by Polpetta** [comment]
Ok!
