### ISSUE TITLE
Spostare immagine processo gestione del rischio

### ISSUE THREAD

**Issue by tfederico** [Polpetta/SecurityAndRiskManagementNotes#9]
Dove mettiamo l'immagine a pagina 68?

**Comment by herrBez** [comment]
È l'immagine 6.2 della release 0.14?

**Comment by Polpetta** [comment]
Non lo so. Sinceramente è cambiato così tanto dal 7/07 che per capire bisognerebbe andare a compilare una versione del pdf in quella data (bisogna tornare indietro su git per capire cosa intendeva @tfederico)
