### ISSUE TITLE
Sezione 5.4.2 Footnote vacante

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#91]
**Description**
La sezione 5.4.2 inizia con una footnote che non capisco nemmeno se abbia senso?
**Other issues**

**Comment by mzanella** [comment]
Non so secondo me si potrebbe iniziare la sezione dicendo tipo
> Con il termine \textit{black hat} si intende in generale un attaccante ad un sistema informatico con fini illeciti.

o forse meglio spostandolo dove si parla degli attacchi

**Comment by Polpetta** [comment]
So che è un po' bruttino ma non sapevo dove mettere quell'appunto altrimenti

**Comment by herrBez** [comment]
Beh cosí non porta nessun contributo secondo me. Black Hat viene citato solo nella footnote. Già con una frase nel testo sembra che serva a qualcosa

**Comment by herrBez** [comment]
Quindi che abbiamo deciso?

**Comment by Polpetta** [comment]
A sto punto è meglio metterlo come testo normale che come footnote se dite che è troppo brutto
