### ISSUE TITLE
Sezione 6.3.1.4 What's the HIPAA

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#92]
**Description**
> Il costo di un incidente HIPAA con protezioni insufficienti:

Leggendo il testo non è molto chiara la frase, soprattutto HIPAA che non viene mai introdotto.
**Other issues**

**Comment by Polpetta** [comment]
È un esempio che indica cosa succede nel caso di sto tipo di incidente (che non so manco io cosa sia) quando non si hanno prese le dovute precauzioni riguardo alla gestione del rischio.

Boh io non ci ho dato importanza, è un esempio anche se non so bene cosa significa amen

**Comment by Polpetta** [comment]
C'è se lo trovi meglio però, ci piazziamo un footnote e problema risolto! 😊

**Comment by mzanella** [comment]
Potrebbe essere una legge americana con una serie di articoli _che stabiliscono uno standard di sicurezza per lo scambio di dati elettronici. In particolare, la sicurezza e il riservo di tutte le informazioni medico-sanitarie._? (Ho trovato questo che centra cercando in internet)

**Comment by Polpetta** [comment]
Ehm...non saprei proprio 😅

**Comment by Polpetta** [comment]
Da chiedere al prof? 😁

**Comment by herrBez** [comment]
Nel libro CISA Study Guide dice che:
![image](https://user-images.githubusercontent.com/6976484/29189625-882da242-7e17-11e7-8bc9-830ab6cdd7ff.png)
(La seconda colonna è lo scopo, mentre l'ultima colonna è l'applicazione)

**Comment by Polpetta** [comment]
Allora probabilmente la tabella è un esempio
