### ISSUE TITLE
Frase di introduzione non chiarissima/da riscrivere

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#93]
**Description**
Secondo me questa frase non è molto chiara:

> Quanto è importante investire nella sicurezza? La sicurezza è sempre più “venduta”
e comunicata come il classico ROI . C’è anche un altro fattore da tenere conto, la
pubblicità: la cattiva pubblicità è devastante per un’azienda e può danneggiare molto
facilmente la fiducia degli utenti. Si stima che ci sia un ritorno dell’investimento
del 5%.

Soprattutto la parte:

> La sicurezza è sempre più “venduta”
e comunicata come il classico ROI 

e inoltre invece di utenti userei clienti. 

Cosa ne pensate?

**Other issues**

**Comment by Polpetta** [comment]
Non capisco cosa non sia chiaro in
> la sicurezza è sempre più "venduta" e comunicata come il classico ROI (return of investment) 

Se vuoi usare clienti va bene

**Comment by herrBez** [comment]
Cosa vuol dire "come il classico ROI" (all'interno della frase). Cioè (togliendo il sempre più venduta):
La sicurezza è comunicata come il classico ROI

Forse è chiara ma adesso leggendola cosí non riesco a capirla :sweat_smile: 
La lascio cosí ma se me la riformuli un secondo per farmela capire ne sarei felice :smile:
