### ISSUE TITLE
Elenco sulla tipologia di controllo ripetuta due volte nella stessa frase

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#94]
**Description**
Sostanzialmente c'è un elenco puntato che indica le tipologie di controllo e subito dopo c'è di nuovo l'elenco con la spiegazione:

***Ora***:

![image](https://user-images.githubusercontent.com/6976484/29205035-b1a2ce6e-7e7a-11e7-8f96-c6e9a35778db.png)

***Dopo la modifica che vorrei introdurre***

![image](https://user-images.githubusercontent.com/6976484/29205064-dc342268-7e7a-11e7-9eb1-ac05b6d66c32.png)

**Other issues**
#54

**Comment by mzanella** [comment]
Vai per me... io l'avevo lasciato ma in effetti è ridondante
