### ISSUE TITLE
Plurale delle paroli inglesi

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#96]
**Description**
Nei testi italiani le paroli inglesi non andrebbero declinate al plurale:
http://www.treccani.it/magazine/lingua_italiana/domande_e_risposte/grammatica/grammatica_391.html
Nel capitolo 6 è pieno di plurali di `asset` che vengono scritti come `assets`.
Vi da fastidio se correggo e in generale se cercherò di cancellare tutti i plurali inglesi?
**Other issues**

**Comment by mzanella** [comment]
No vai pure ma attenzione a tenere tale branch aggiornato se facciamo merge in develop

**Comment by herrBez** [comment]
Certo! Ma non penso che oggi cercherò di andare avanti (prometto che dopo le sistemo :stuck_out_tongue_winking_eye:

**Comment by Polpetta** [comment]
Sisi sistema pure!
