### ISSUE TITLE
Riferimenti alle figure in maiuscolo?

### ISSUE THREAD

**Issue by herrBez** [Polpetta/SecurityAndRiskManagementNotes#97]
**Description**
Da come mi aveva detto a suo tempo De Giovanni i riferimenti alle figure (ma anche ai capitoli, tabelle ecc.)  andrebbero scritte in maiuscolo (perchè sono "dei nomi propri"). 
Per esempio:
`come mostrato nella figura 7.1` andrebbe scritto secondo questa convenzione come `come mostrato nella Figura 7.1`. 

Anche se è un po' controversa la cosa: https://writers.stackexchange.com/questions/5482/referencing-figure-in-text-capitalize-the-word-figure-or-not-why

Secondo me l'importante è decidere una convenzione ed essere consistenti con quella. 
Voi quale preferite?
**Other issues**

**Comment by mzanella** [comment]
A me piace più il maiuscolo

**Comment by Polpetta** [comment]
Anche per me, vai con quello! 😊 👍
